### ISSUE TITLE
ActionSequence shrinking to nothing

### ISSUE THREAD

**Issue by jdmarble** [jlink/jqwik#104]
## Testing Problem

I'm using [stateful testing](https://jqwik.net/docs/current/user-guide.html#stateful-testing) and some, but not all of my actions have preconditions that reject my model when it has been shrunk to the extreme. Some of my other actions have assertions that are checked when they are run. If those assertions always pass, everything works as expected. If one of them fails, I usually get something like this:

```
net.jqwik.api.JqwikException: Could not generated a single action. At least 1 is required.

                              |--------------------jqwik--------------------
tries = 39                    | # of calls to property
checks = 39                   | # of not rejected calls
generation-mode = RANDOMIZED  | parameters are randomly generated
after-failure = PREVIOUS_SEED | use the previous seed
seed = 2674951227541351268    | random seed to reproduce generated values
sample = [ActionSequence: [], MyShrunkModel]
original-sample = [ActionSequence[FAILED]: [...lots of actions...], MyUnshrunkModel]
```

I think what is happening is the assertion in one of the running actions fails and jqwik shrinks the action sequence and model until there are no actions that pass preconditions.

I've been working around the problem by breaking on assertions before the shrinking happens. Another work-around might be for me to move the preconditions into the run methods of the actions and simply not perform the actions if the precondition fails.

## Suggested Solution

Perhaps shrinking can be aborted as soon as there are no actions in the sequence that pass the preconditions. Then the last failure is reported.

## Discussion

Honestly, I'm not even sure if my proposed root cause is the actual problem. Fixing my code-under-test so the assertions pass never results in a "Could not generated a single action. At least 1 is required." exception. So, that's some evidence.

Let me know if you need a minimal example that triggers the problem.

**Comment by jlink** [comment]
Thanks for the catch!

In theory an action sequence should never be shrunk to an empty sequence because that does not make sense. My current inkling is that it will be shrunk - as you assume - to a sequence with all remaining actions having failing preconditions. I'll have a look into that and get back to you.

**Comment by jlink** [comment]
@jdmarble 
I couldn't really reproduce the behaviour you describe but I made an informed guess why it happended and hopefully fixed it.

Can you try it with version '1.3.0-SNAPSHOT'? Maven repo is 'https://oss.sonatype.org/content/repositories/snapshots'

If it still shows the same behaviour I'd appreciate a minimal example.

**Comment by jlink** [comment]
BTW, the previous close was a mistake.

**Comment by jdmarble** [comment]
I introduced a failure that would trip an action post-condition and the problem in version `1.2.7`. I verified that it triggered the problem in version `1.2.7` then tried it with `1.3.0-SNAPSHOT`. I got different, but not good results:

```
org.opentest4j.AssertionFailedError: Property [MyTest:myTest] failed with sample [ActionSequence: [], MySmallerModel]

                              |--------------------jqwik--------------------
tries = 52                    | # of calls to property
checks = 52                   | # of not rejected calls
generation = RANDOMIZED       | parameters are randomly generated
after-failure = PREVIOUS_SEED | use the previous seed
edge-cases = MIXIN            | edge cases are mixed in
seed = -948910638269924509    | random seed to reproduce generated values
sample = [ActionSequence: [], MySmallerModel]
original-sample = [ActionSequence[FAILED]: [...many actions..., MySmallModel]


org.opentest4j.AssertionFailedError: Property [MyTest:myTest] failed with sample [ActionSequence: [], MySmallModel]

	at net.jqwik.engine@1.3.0-20200511.134526-13/net.jqwik.engine.properties.PropertyCheckResult.determineThrowable(PropertyCheckResult.java:135)
```

There's no indication where the actual bug that I introduced is or which assertions were triggered. If I remove the intentional bug, the tests pass with both versions `1.2.7` and `1.3.0-SNAPSHOT` of jqwik.

I will attempt to create a minimal example now.

**Comment by jdmarble** [comment]
I have captured [a minimal example](https://gist.github.com/jdmarble/8d9b4ca3b349eb6a3b5105a10b7bd9cd)!

With version `1.2.7` I get the following output:

```
net.jqwik.api.JqwikException: Could not generated a single action. At least 1 is required.

                              |--------------------jqwik--------------------
tries = 1                     | # of calls to property
checks = 1                    | # of not rejected calls
generation-mode = RANDOMIZED  | parameters are randomly generated
after-failure = PREVIOUS_SEED | use the previous seed
seed = 2778409285821134537    | random seed to reproduce generated values
sample = [ActionSequence: [], org.example.jqwikactionsshrinktonothing.JqwikActionsShrinkToNothing$MyStringStack@2034b64c]
original-sample = [ActionSequence[FAILED]: [org.example.jqwikactionsshrinktonothing.JqwikActionsShrinkToNothing$PopAction@209da20d, org.example.jqwikactionsshrinktonothing.JqwikActionsShrinkToNothing$$Lambda$349/0x00000008001b8c40@e15b7e8], org.example.jqwikactionsshrinktonothing.JqwikActionsShrinkToNothing$MyStringStack@1b2abca6]
```

And with version `1.3.0-SNAPSHOT`:

```
org.opentest4j.AssertionFailedError: Property [JqwikActionsShrinkToNothing:checkMyStack] failed with sample [ActionSequence: [], org.example.jqwikactionsshrinktonothing.JqwikActionsShrinkToNothing$MyStringStack@16eb3ea3]

                              |--------------------jqwik--------------------
tries = 1                     | # of calls to property
checks = 1                    | # of not rejected calls
generation = RANDOMIZED       | parameters are randomly generated
after-failure = PREVIOUS_SEED | use the previous seed
edge-cases = MIXIN            | edge cases are mixed in
seed = 2778409285821134537    | random seed to reproduce generated values
sample = [ActionSequence: [], org.example.jqwikactionsshrinktonothing.JqwikActionsShrinkToNothing$MyStringStack@16eb3ea3]
original-sample = [ActionSequence[FAILED]: [org.example.jqwikactionsshrinktonothing.JqwikActionsShrinkToNothing$PopAction@b9b00e0, org.example.jqwikactionsshrinktonothing.JqwikActionsShrinkToNothing$$Lambda$366/0x00000008001c4840@506ae4d4], org.example.jqwikactionsshrinktonothing.JqwikActionsShrinkToNothing$MyStringStack@7d4f9aae]




org.opentest4j.AssertionFailedError: Property [JqwikActionsShrinkToNothing:checkMyStack] failed with sample [ActionSequence: [], org.example.jqwikactionsshrinktonothing.JqwikActionsShrinkToNothing$MyStringStack@16eb3ea3]

	at net.jqwik.engine.properties.PropertyCheckResult.determineThrowable(PropertyCheckResult.java:135)
```

Thank you for looking at this, and for this library in general!

**Comment by jlink** [comment]
I am working on it. It's a tough one. I've already found and fixed a bug in ActionSequence shrinking. Sadly, it's not the one causing your problem. Stay tuned.

**Comment by jlink** [comment]
@jdmarble 
I hopefully fixed the bug and also improved shrinking of dependent parameters as in your minimal example. Please try with latest 1.3.0-SNAPSHOT.

**Comment by jdmarble** [comment]
That fixed it for me! Thank you very much for your work on this!
