### ISSUE TITLE
Is jqwik compatible with other engines? (vintage, jupiter, etc.)

### ISSUE THREAD

**Issue by nicolascouvrat** [jlink/jqwik#109]
## Testing Problem

I'm having a bunch of tests running in a mixture of Junit5 and Junit4 (using the vintage engine). I would like to use jqwik to test a new file, but I do not want to touch existing tests.

I had issues where `mvn test` would either run `jqwik`, or `junit`, but not both. I tried to reproduce it in the `starter-maven` sample, by adding the following to the `pom`

```
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-engine</artifactId>
            <version>5.1.0</version>
            <scope>test</scope>
        </dependency>
```

I then ran `mvn test`, and got:

```
May 30, 2020 7:31:15 PM org.junit.platform.launcher.core.DefaultLauncher handleThrowable
WARNING: TestEngine with ID 'jqwik' failed to discover tests
java.lang.NoSuchMethodError: org.junit.platform.engine.EngineDiscoveryRequest.getDiscoveryListener()Lorg/junit/platform/engine/EngineDiscoveryListener;
	at net.jqwik.engine.discovery.JqwikDiscoverer.discover(JqwikDiscoverer.java:30)
	at net.jqwik.engine.JqwikTestEngine.discover(JqwikTestEngine.java:50)
	at org.junit.platform.launcher.core.DefaultLauncher.discoverEngineRoot(DefaultLauncher.java:168)
	at org.junit.platform.launcher.core.DefaultLauncher.discoverRoot(DefaultLauncher.java:155)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:128)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invokeAllTests(JUnitPlatformProvider.java:150)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invoke(JUnitPlatformProvider.java:124)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
```

I'm running on MacOS, with this version of Java:

```
@dragonfruit:~/qwik-samples/jqwik-starter-maven (master) *$ mvn -v
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /usr/local/Cellar/maven/3.6.3/libexec
Java version: 1.8.0_232, vendor: Amazon.com Inc., runtime: /Library/Java/JavaVirtualMachines/amazon-corretto-8.jdk/Contents/Home/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.15.4", arch: "x86_64", family: "mac"
```

I thought jqwik was just another engine that I can use together (in different files, of course) with the other ones, but am I mistaken?

## Suggested Solution

I dont know...

## Discussion

I apologize if the answer to this is obvious, but I've spent a fair amount of time googling around and reading the documentation without finding anything :/

**Comment by jlink** [comment]
There’s no compatibility problem with other engines (that I know of). 

I guess you have to get the dependencies sorted out. There’s a multi engine starter project: https://github.com/junit-team/junit5-samples/tree/master/junit5-multiple-engines

You cannot use it directly since it’s using Gradle but you can lookup the required dependencies in the Gradle file. You need at least jqwik and junit-vintage-engine, which is required to run JUnit4 tests on the JUnit 5 platform. 

If you don’t get along I may create a multi project starter for Maven one of these days...

**Comment by nicolascouvrat** [comment]
Thanks! The link you gave me provided me with a hint: the problem was (and in fact, is) transitive dependencies (and dependency mediation).

All Junit5 engines, including the vintage one and jqwik, seem to depend on `org.junit.platform:junit-platform-engine:jar`. The problem is, I was trying to use the engine v5.1.0, which comes with v1.1.0 of said `org.junit.platform:junit-platform-engine:jar:1.2.0:test`, while jqwik (both 1.2.7 and 1.3.0) depend on v1.6.2.

And because the dependency path for jqwik is longer (`jqwik`>`jqwik-api`>`junit-platform-engine`), dependency mediation was chosing v1.1.0, killing jqwik in the process.

I've tried using the [Junit5 BOM](https://mvnrepository.com/artifact/org.junit/junit-bom), which does make dependency resolution cleaner, but this does not change the fact that **the `junit-platform-engine` version must be compatible**, meaning 1.6.1 and up as far as I could test.

I'm opening a pull request on the sample repository [here](https://github.com/jlink/jqwik-samples/pull/1).

**Comment by jlink** [comment]
So it's more complicated than I thought :-(
I'll review the PR in the near future. Thank you!
