### ISSUE TITLE
Per class life cycle with jersey test framework

### ISSUE THREAD

**Issue by dsvensson** [jlink/jqwik#110]
I was hoping to use jqwik for testing a REST API, but the hugeisch code base currently uses Jersey Test Framework base class that performs the expensive setup once per class, and exposes a client to the test suite. Just calling the base class setUp() function is not enough, and possibly to make matters worse, jersey test frameworkis not on junit 5 yet, so there might be some weirdness with junit-vintage as well.

Your documentation suggested that I filed a bug about other-than-method life cycles, so here it is!

**Comment by jlink** [comment]
Thanks for raising that issue. Might be a good example to check the usability of jqwik‘s hooks API. 

Can you provide a link to the Jersey Testing framework and maybe a minimum example to run it?

**Comment by dsvensson** [comment]
There actually is a small example in this PR, 

https://github.com/eclipse-ee4j/jersey/pull/4351

The way it adds Jupiter-support is not that great though but the example should be a good starting point, changing that example to inhereting JerseyTest is what is done today, and it gets the super.target(urlpath) for calling into the webserver hosting the app.

**Comment by jlink** [comment]
@dsvensson I'll have a look at it to get a feel for how much effort a jersey jqwik-hook would entail.
Would you be interesting to publish one with my support?

**Comment by dsvensson** [comment]
@jlink sure

Pushed a small test repo here, https://github.com/dsvensson/resttest

**Comment by jlink** [comment]
@dsvensson I cloned the repo. The two properties fail - I guess that's intended.

I'll sketch a raw jqwik Jersey extension and we can discuss it.

**Comment by dsvensson** [comment]
Should have added a README to explain it a bit I guess :)

I'm printing a random int as well, with the intention for it to be the same in all junit tests, and the properties per class, or at least the same for all properties per class.

**Comment by jlink** [comment]
I assume that you want to get away from the base class approach. Otherwise you could just go with your example or does it have any functional drawbacks?

Without a base class one has to find a way to set up the jersey context and a means to access target and client? The simplest approach I see is to provide some kind of configurer that can then be used in a lifecycle method and a JerseyTest instance could be injected as parameter. 

Here's a sketch:

```java
@AddLifecycleHook(JerseyHook::class)
class RestProperties {

    @BeforeProperty
    fun initializeJersey(configurer: JerseyConfigurer) {
        configurer
                .withTestContainerFactory(GrizzlyWebTestContainerFactory())
                .withDeployment(ServletDeploymentContext.forServlet(ServletContainer(ResourceConfig().register(SimpleResource()))).build())
                .configure();
    }

    @Property
    fun testProper(jerseyTest: JerseyTest, @ForAll a: Int, @ForAll b: Int) {
        val actual = jerseyTest.target("simple")
                .queryParam("a", a)
                .queryParam("b", b)
                .request()
                .get()
                .readEntity(Int::class.java)
        assertEquals(a + b, actual)
    }

    @Property
    fun testProper2(jerseyTest: JerseyTest, @ForAll a: Int, @ForAll b: Int) {
        val actual = jerseyTest.target("simple")
                .queryParam("a", a)
                .queryParam("b", b)
                .request()
                .get()
                .readEntity(Int::class.java)
        assertEquals(a + b, actual)
    }
}
```

Would that suit your needs? Do you a different suggestion?

**Comment by dsvensson** [comment]
My example has the drawback of the instance not being the same all four tests+props. The two junit tests use the same jersey instance, the two properties each use a new instance.

As it's expensive to setup jersey in the real use case (flyway cleanup, hibernate etc), my goal is to avoid that and just setup jersey once per class, and then test against that same instance.

It wouldn't be any problem to split up the PBT based tests from Junit tests in different class files, I will have enough properties to overcome the overhead of setting it up. Just want to avoid the setup per property.

**Comment by jlink** [comment]
If that's your main problem I have a simpler solution:

```kotlin
class RestProperties {

    private class JqwikJerseyTest : JerseyTest() {
        override fun getTestContainerFactory(): TestContainerFactory =
                GrizzlyWebTestContainerFactory()

        override fun configureDeployment(): DeploymentContext =
                ServletDeploymentContext.forServlet(ServletContainer(ResourceConfig().register(SimpleResource()))).build()
    }

    companion object {
        private lateinit var jerseyTest: JqwikJerseyTest

        @BeforeContainer
        @JvmStatic
        fun initializeJersey() {
            jerseyTest = JqwikJerseyTest();
            jerseyTest.setUp();
        }

        @AfterContainer
        @JvmStatic
        fun tearDownJersey() {
            jerseyTest.tearDown();
        }
    }

    @Property
    fun testProper(@ForAll a: Int, @ForAll b: Int) {
        val actual = jerseyTest.target("simple")
                .queryParam("a", a)
                .queryParam("b", b)
                .request()
                .get()
                .readEntity(Int::class.java)
        assertEquals(a + b, actual)
    }

    @Property
    fun testProper2(@ForAll a: Int, @ForAll b: Int) {
        val actual = jerseyTest.target("simple")
                .queryParam("a", a)
                .queryParam("b", b)
                .request()
                .get()
                .readEntity(Int::class.java)
        assertEquals(a + b, actual)
    }
}
```

This is not elegant but seems to work. And it's probably not very Kotlin-like - it's my first self-written Kotlin class :-)

I think that an elegant, not class-based, solution for jqwik (and for JUnit 5 Jupiter) would require some change to the testing API of JerseyTest to make it more suitable for parameter injection. But that's probably out of scope.

**Comment by dsvensson** [comment]
That can ofc actually work. I was stuck in the mindset of these tests working the same way as the junit ones in the project I'm working on, and it would be extremely painful to do that change to the whole set of tests as it's less minimalistic than my example.

For the properties I'm aiming for it would be trivial to do as you suggest.

Blinded by the existing structure - the eternal enemy. Thanks for poking a hole in that bubble.

**Comment by jlink** [comment]
Seems like your actual problem is solved. Feel free to reopen if I'm wrong.
