### ISSUE TITLE
"Cannot find Arbitrary" with maven-failsafe-plugin 3.0.0-M5

### ISSUE THREAD

**Issue by tmohme** [jlink/jqwik#112]
## Testing Problem

When using jqwik together with the maven-failsafe-plugin 3.0.0-M5 and its parameter "fork-count" != 0, then jqwik is unable to find the configured custom Arbitraries.

## Suggested Solution

My guess is, that it is a problem with the maven-failsafe-plugin, as the following combinations work flawless:
* maven-failsafe-plugin 3.0.0-M5 and "fork-count" == 0
* maven-failsafe-plugin 2.22.2
* running the corresponding tests in a IDE
* running similar tests with the maven-surefire-plugin 3.0.0-M5 (sic!)

These variations can be used as workarounds.

## Discussion

As mentioned above I suspect the problem's root cause within the maven-failsafe-plugin.  
Unfortunately I'm unable to find a way to report the problem to its maintainers. 
Although I don't think that the problem will be resolved by jqwik, this report might help others to _not_ spend hours searching for the cause of the issue in their code.

**Comment by jlink** [comment]
Thanks for reporting!
What does `fork-count` specify?

**Comment by jlink** [comment]
I think Maven's communication with its community works through the Apache Slack: https://the-asf.slack.com/
But that's just a guess.

**Comment by tmohme** [comment]
`fork-count` specifies whether (and how many) JVMs should be forked to run the tests.  
The value `0` means: "Do not fork a new JVM, run the tests in this JVM" . . . which for sure has some influence on class-loading / resource-loading behavior.

**Comment by jlink** [comment]
"configured custom Arbitraries": do you mean Arbitrary provider classes registered through Java's SPI mechanism?

**Comment by tmohme** [comment]
Exactly.
```
  net.jqwik.api.CannotFindArbitraryException:
    Cannot find an Arbitrary for Parameter of type [@net.jqwik.api.ForAll(value="") MyCustomClass]
```
`MyCustomClass` is a domain class for which I have registered an ArbitraryProvider via Java's SPI mechanism.

**Comment by jlink** [comment]
Sounds like failsafe does not handle SPI correctly.

**Comment by jlink** [comment]
Closing since it seems not to be a jqwik bug. Feel free to reopen if new information suggests otherwise.
