### ISSUE TITLE
Always getting Error "No Jqwik properties file [jqwik.properties] found"

### ISSUE THREAD

**Issue by Serranya** [jlink/jqwik#115]
Im using jqwik 1.3.2 with maven. When the tests run I get the following error:
```
INFO] --- maven-surefire-plugin:3.0.0-M5:test (default-test) @ condorcat ---
[INFO]
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[ERROR] Juli 29, 2020 4:41:04 PM net.jqwik.engine.JqwikProperties loadProperties
[ERROR] INFORMATION: No Jqwik properties file [jqwik.properties] found.
[INFO] Running de.serra.condorcat.model.InMemoryBallotStorePropertiesTest
timestamp = 2020-07-29T16:41:27.295662, InMemoryBallotStorePropertiesTest:itHasAllEntries =
                              |-------------------jqwik-------------------
tries = 1000                  | # of calls to property
checks = 1000                 | # of not rejected calls
generation = RANDOMIZED       | parameters are randomly generated
after-failure = PREVIOUS_SEED | use the previous seed
edge-cases#mode = MIXIN       | edge cases are mixed in
edge-cases#total = 1          | # of all combined edge cases
edge-cases#tried = 1          | # of edge cases tried in current run
seed = 5295101792625370932    | random seed to reproduce generated values
[...]
```

I do have a `jqwik.properties` properties file at the same level as my `pom.xml` but it is not respected.

I took a look at https://github.com/jlink/jqwik/blob/5217b8e8d6fc7379c08ab077354c1989da9a16ea/engine/src/main/java/net/jqwik/engine/JqwikProperties.java#L96-L100 and it looks like only the contents of the .jar are searched (if I understand #getResourceAsStream correctly).

How can I make jqwik read my properties and get rid of the error?

**Comment by luvarqpp** [comment]
Have you tried `src/test/resources` folder? I have it there and execution detects it also during `mvn test` execution.

**Comment by Serranya** [comment]
Ahh my fault. The docs even state explicitly that the file needs to be in the classpath.

**Comment by jlink** [comment]
I love it when users help each other :-)
