### ISSUE TITLE
Could/should ListArbitrary::map produce an Arbitrary that supports @Size?

### ISSUE THREAD

**Issue by daniel-huss** [jlink/jqwik#120]
## Testing Problem

We're using jqwik's awesome ability to create arbitrary data structures via the `Arbitrary::forType` facility. In some cases, creation of those data structures explicitly requires instances of `ImmutableList<T>` instead of just `List<T>` (which we can't change). OK, such an Arbitrary is easily provided via `Arbitrary.map(ImmutableList::copyOf)`. The overhead of copying the list doesn't matter to us.

```kotlin
import com.google.common.collect.ImmutableList
import net.jqwik.api.Arbitrary
import net.jqwik.api.providers.TypeUsage
import net.jqwik.engine.providers.ListArbitraryProvider

class ImmutableListArbitraryProvider : ListArbitraryProvider() {
    override fun canProvideFor(typeUsage: TypeUsage) = typeUsage.isOfType(ImmutableList::class.java)
    override fun getProvidedType() = ImmutableList::class.java
    override fun create(innerArbitrary: Arbitrary<*>) = innerArbitrary.list().map { ImmutableList.copyOf(it) }
}
```

However, `ListArbitrary::map` seems to fall back to the default implementation of `Arbitrary::map`, which of course doesn't return a `SizableArbitrary`. So using `@Size` is not going to work. 

```java
import static org.junit.jupiter.api.Assertions.assertAll;
import static org.junit.jupiter.api.Assertions.assertTrue;

import com.google.common.collect.ImmutableList;
import java.util.Set;
import net.jqwik.api.Arbitraries;
import net.jqwik.api.arbitraries.SizableArbitrary;
import net.jqwik.api.providers.TypeUsage;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.function.Executable;

class ImmutableListArbitraryProviderTest {
    @Test
    void provideFor_Always_ReturnsInstancesOfSizeableArbitrary() {
        // given
        var provider = new ImmutableListArbitraryProvider();
        // when
        var arbitraries = provider.provideFor(TypeUsage.of(ImmutableList.class,
                                                           TypeUsage.forType(String.class)),
                                              it -> Set.of(Arbitraries.defaultFor(it)));
        // then
        assertAll(arbitraries.stream()
                      .<Executable>map(it -> () ->
                          assertTrue(it instanceof SizableArbitrary, it.getClass() + " is sizeable"))
                      .toArray(Executable[]::new));
    }
}
```

This quickly leads to OOM and/or slow test execution when a `@Property` test works with nested data structures.

(using jqwik version 1.3.5)

## Suggested Solution

I'm not sure if this is feasible, but if `StreamableArbitrary::map` could be made to return an instance of StreamableArbitrary then my understanding is that the @Size constraint would automatically work. 

## Discussion
Above suggestion is just what (to me) seemed the be the most obvious option from looking at the type hierarchy. I don't really have an opinion or valuable input when it comes to the actual solution. I'll update the issue if I get to author something pull-request-worthy this weekend.

**Comment by daniel-huss** [comment]
I think because of erasure this isn't going to be possible the way I imagined it.

```java
	@Override
	public <X> Arbitrary<X> map(Function<U, X> mapper) {
		// Can't tell if <X> is multi-valued.
	}
```
More specialized mapping methods could be added to ListArbitrary, SetArbitrary, etc. but that's probably overkill for such an exotic use case. I'd like to withdraw this feature request. Thank you very much for your time and have a nice weekend :)

**Comment by jlink** [comment]
@daniel-huss Yes, the approach you’ve chosen does not work because of type erasure. 

What you can do, however, is return your own implementation of StreamableArbitrary, eg which delegates to a base listArbitrary and only does the mapping as soon as the generator is being created. I could work out a sketch if you want to follow that route.
