### ISSUE TITLE
Support for Coarbitrary

### ISSUE THREAD

**Issue by larsrh** [jlink/jqwik#123]
## Testing Problem

I need to generate a random function.

## Suggested Solution

Port `Coarbitrary` from Quick- or ScalaCheck.

## Discussion

Currently, the way to do this in Jqwik is quite hard. One needs to create a custom function with a "memory" of already generated values. This is bad for many reasons, including mutability and concurrency problems.

**Comment by jlink** [comment]
@larsrh Could you show a simple example?

**Comment by larsrh** [comment]
In Scala:

```
@ import $ivy.`org.scalacheck::scalacheck:1.14.0` 
import $ivy.$                                  

@ import org.scalacheck._ 
import org.scalacheck._

@ val arb = implicitly[Arbitrary[String => Int]].arbitrary 
arb: Gen[String => Int] = org.scalacheck.Gen$$anon$5@58606c91

@ val f = arb.sample.get 
f: String => Int = org.scalacheck.GenArities$$Lambda$1449/0x000000010084f040@202d9236

@ f("a") 
res5: Int = -614099726

@ f("b") 
res6: Int = -2147483648

@ f("a") 
res7: Int = -614099726
```

**Comment by jlink** [comment]
Maybe I don't get it, but maybe you are talking about https://jqwik.net/docs/current/user-guide.html#functional-types

**Comment by jlink** [comment]
To copy your example above:

		Arbitrary<Function<String, Integer>> arb =
			Functions.function(Function.class).returns(Arbitraries.integers());

		Function<String, Integer> f = arb.sample();

		System.out.println(f.apply("a")); // -3553
		System.out.println(f.apply("b")); // -4007168
		System.out.println(f.apply("a")); // -3553

**Comment by larsrh** [comment]
You're absolutely right! I was looking for `Coarbitrary` in the docs, but didn't find it. It didn't occur to me to look for functions specifically. Apologies for the noise.

**Comment by jlink** [comment]
In theory it’s a Co-Arbitrary. In practice it’s used to generate functions. ;-)
