### ISSUE TITLE
Provide convenience method for email generation

### ISSUE THREAD

**Issue by jlink** [jlink/jqwik#127]
## Testing Problem

Generating valid emails (as Strings) is a common task but requires to combine a few string generators into a single string.
I'd like to have a straightforward way to generate emails.

## Suggested Solution

- Provide a method `Arbitraries.emails()` for generating valid email addresses. Valid according to some standard (might be RFC 5322 and 6854).
- Additionally have an `@Email` annotation to simplify using this arbitrary.

## Discussion

- `Arbitraries.emails()` seems to be the obvious place, but maybe `StringArbitrary.emails()` is better?
- Does email generation require configuration (length, special chars, top level domain, etc.)? In that case an new API interface
  `EmailArbitrary` would have to be introduced. That might be an advanced feature.

**Comment by zinki97** [comment]
I am working on it:
https://github.com/jlink/jqwik/pull/128

**Comment by jlink** [comment]
Done and available in 1.3.8-SNAPSHOT.

Many thanks @zinki97!
