### ISSUE TITLE
Problem using more Combinators.combine() and oneOf/frequencyOf at the same time

### ISSUE THREAD

**Issue by zinki97** [jlink/jqwik#129]
I think both properties should work, but one property isn't working. The only difference in the code is, that I combine more arbitraries in the code that isn't working. (`Combinators.combine(Arbitraries.just("."), integer, integer, integer).as((a, b, c, d) -> a + b + c + d);` instead of `Combinators.combine(Arbitraries.just("."), integer).as((a, b) -> a + b);)`

The more integers you combine, the more the result diverges.

Thanks for helping

```
import net.jqwik.api.statistics.*;

public class TestForIssue {

	@Property
	void propertyWorks(@ForAll("isWorking") String string){
		Statistics.collect(string.charAt(10) == '.');
		Statistics.coverage(coverage -> {
			coverage.check(true).count(c -> c >= 300); //ca. 50%
			coverage.check(false).count(c -> c >= 300); //ca. 50%
		});
	}

	@Provide
	Arbitrary<String> isWorking() {
		Arbitrary<String> a = Arbitraries.strings().numeric().ofLength(10);
		Arbitrary<String> b = Arbitraries.strings().alpha().ofLength(10);
		Arbitrary<String> string1 = Arbitraries.oneOf(a, b);
		Arbitrary<String> string2 = isWorking2();
		return Combinators.combine(string1, string2).as((v1, v2) -> v1 + v2);
	}

	Arbitrary<String> isWorking2(){
		Arbitrary<Integer> integer = Arbitraries.integers().between(0, 255);
		Arbitrary<String> integerCombinated = Combinators.combine(Arbitraries.just("."), integer).as((a, b) -> a + b);
		Arbitrary<String> string = Arbitraries.strings().alpha().ofLength(10);
		return Arbitraries.oneOf(integerCombinated, string);
	}

	@Property
	void propertyWorksNot(@ForAll("isNotWorking") String string){
		Statistics.collect(string.charAt(10) == '.');
		Statistics.coverage(coverage -> {
			coverage.check(true).count(c -> c >= 300); //ca. 87%
			coverage.check(false).count(c -> c >= 300); //ca. 13%
		});
	}

	@Provide
	Arbitrary<String> isNotWorking() {
		Arbitrary<String> a = Arbitraries.strings().numeric().ofLength(10);
		Arbitrary<String> b = Arbitraries.strings().alpha().ofLength(10);
		Arbitrary<String> string1 = Arbitraries.oneOf(a, b);
		Arbitrary<String> string2 = isNotWorking2();
		return Combinators.combine(string1, string2).as((v1, v2) -> v1 + v2);
	}

	Arbitrary<String> isNotWorking2(){
		Arbitrary<Integer> integer = Arbitraries.integers().between(0, 255);
		Arbitrary<String> integerCombinated = Combinators.combine(Arbitraries.just("."), integer, integer, integer).as((a, b, c, d) -> a + b + c + d);
		Arbitrary<String> string = Arbitraries.strings().alpha().ofLength(10);
		return Arbitraries.oneOf(integerCombinated, string);
	}

}
```

**Comment by jlink** [comment]
@zinki97 Thanks for reporting that! I'll have a look at it.

**Comment by jlink** [comment]
The behaviour you observe is triggered by jqwik's tendency to distort distributions towards edge cases.
So you can "fix" it by switching edge cases of:

```
	@Property(edgeCases = EdgeCasesMode.NONE)
	void propertyWorksNot(@ForAll("isNotWorking") String string){
		...
	}
```

However, I'm currently not sure if in this case this is intended distortion or not. I'll do a bit more research.

**Comment by jlink** [comment]
The behaviour you observe is indeed as designed (which does not mean that it can't or shouldn't be changed).

What jqwik does, when edge cases are not disabled, is to mix in edge cases with some probability. 
Since `integerCombinated` has more edge cases than `string` `Aribitraries.oneOf()` will mix-in more of the former than the latter.

In your case you are probably running with `EdgeCasesMode.FIRST` as default (have a look at your application.properties file) which will distort the distribution even stronger since all edge cases are tried first before any randomly generated input is used.

I could imagine to change `Aribitraries.oneOf()` in such a way that it will inject edge cases from all branches with uniform distribution but that's not an easy change to make.
