### ISSUE TITLE
Add default generation for String with `@Email` annotation

### ISSUE THREAD

**Issue by jlink** [jlink/jqwik#130]
## Testing Problem

There's currently no way to generate emails just by an annotation.

## Suggested Solution

Register `EmailArbitraryProvider` that reacts to annotation `@Email`.

## Discussion

In the long run `@Email` should have some properties to configure types of email e.g.
`@Email(allowIpv6Domain = false)`

**Comment by zinki97** [comment]
Working on annotation: https://github.com/jlink/jqwik/pull/131

**Comment by jlink** [comment]
Merged PR. Available in 1.3.9-SNAPSHOT. 

See https://jqwik.net/docs/snapshot/user-guide.html#email-address-generation
