### ISSUE TITLE
LazyArbitrary doesn't delegate Arbitrary.exhaustive 

### ISSUE THREAD

**Issue by osi** [jlink/jqwik#137]
The `LazyArbitrary` (as returned by `Arbitraries.defaultFor`) does not override `Arbitrary#exhaustive(long)`

This prevents `allValues()` from working.

**Comment by jlink** [comment]
I seem to remember there’s a reason for that. Will have a closer look later today.

**Comment by jlink** [comment]
Couldn't find a reason (except my lazyness - pun intended) to not allow exhaustive generation.

It's available in 1.4.0-SNAPSHOT.

Bad news: A lot of stuff is planned for 1.4.0, so the release might take a while...

**Comment by jlink** [comment]
has been released in 1.3.10

**Comment by osi** [comment]
thanks!!

-- 
(peter.royal|osi)@pobox.com - http://fotap.org/~osi
