### ISSUE TITLE
Custom Configurators for a Custom Arbitrary

### ISSUE THREAD

**Issue by FeralWhippet** [jlink/jqwik#142]
## Testing Problem

I am testing a class that implements Hypergraph shards, the simplest parameter specification looks something like:

```
    @Property
    void atomPersistance (@ForAll @Size(min=5) Map<@Unique @IntRange(min=1, max=100) Integer,
                                                   @Size(min=0, max=10) List<@IntRange(min=1, max=100) Integer>> edges) {
    }
```

but this does not account for specifying which atoms (atoms represent vertices and edges) are defined locally vs remotely, labelling of atoms, and many other structural properties. The code for mapping those parameters into construction of the shard will become quite complicated, and should not have to be repeated. Furthermore, the Hypergraph objects themselves will become parameters in higher level tests (such as algorithms over the graph, analytics based on the graphs, etc...). Note that I will need additional constraint options beyond `@Size`, etc... When shard objects are used as parameters in additional tests, I am going to need to be able to specify constraints that limit the structure of the graph (for example limiting edges to refer only to vertices, or declaring the graph regular), in order to make tests (runtime) feasible. The structure of the graphs will have to be different for different tests, I want to be able to constrain parameter generation at its declaration for each property test.

So I need to be able to create an arbitrary that constructs shards and can be the target of custom configurators. Is there a way to do that without having to build an Arbitrary implementation from scratch?

## Suggested Solution

Ideally there is already a way for doing this, otherwise I think one possibility could be something like the internal map method inside of Arbitrary.map, that takes a base Arbitrary in addition to the mapping function. In this case, maybe a version of 'map' that takes an arbitrary class / factory / whatever, and an Arbitrary base class similar to combine that can be subclassed for custom arbitraries.

**Comment by jlink** [comment]
I see three features of jqwik that may be of help here:

- Use [self-made annotations](https://jqwik.net/docs/current/user-guide.html#self-made-annotations) 
   to collect annotations that are commonly used together.
- [Create your own configurator](https://jqwik.net/docs/current/user-guide.html#create-your-own-annotations-for-arbitrary-configuration) and combine it with a custom-made annotation
- Collect arbitraries and configurators that belong together [in a domain context](https://jqwik.net/docs/current/user-guide.html#domain-and-domain-context). 
   This one is badly documented (my fault) and will probably go through a fundamental remake one of these days, 
   but [AbstractDomainContextBase.registerConfigurator(..)](https://jqwik.net/docs/1.3.10/javadoc/net/jqwik/api/domains/AbstractDomainContextBase.html#registerConfigurator(net.jqwik.api.configurators.ArbitraryConfigurator)) might be of use to you.

Does one of those or all together answer your needs?

**Comment by jlink** [comment]
@FeralWhippet Feel free to reopen if my answer didn't help or you have additional questions.
