### ISSUE TITLE
per-statistic report format

### ISSUE THREAD

**Issue by osi** [jlink/jqwik#146]
I'm using `Statistics.label(...).collect(...)` to record timing information for each action in a stateful test. I'd like to have these statistics display as a histogram. 

Currently, Using `@StatisticsReport` is a property-wide setting.

In addition to that, offer the ability to specify a reporting format when using `Statistics.label` that would supersede any report format specified as an annotation.

**Comment by jlink** [comment]
Using `Statistics.label(name).withFormat(format)` as you suggest is one option. It would break the current design IDE to move representational/reporting configuration to annotation. Another possibility would be to allow multiple annotations of

`StatisticsReport(label="label1", format=Histogram.class)`
`StatisticsReport(label="label2", format=NumberRangeHistogram.class)`

What do you think?

**Comment by osi** [comment]
Making the annotation repeatable, and allowing it to specify a set of labels to apply to is totally fine. 

I had actually gone to the documentation to see if that was possible before raising this enhancement.

**Comment by jlink** [comment]
I added it to the 1.4.0 timeline

**Comment by jlink** [comment]
Implemented in https://github.com/jlink/jqwik/commit/e6d4c738f2b671b40208141a3a3a3b70075fcffa

**Comment by jlink** [comment]
Available in 1.5.1-SNAPSHOT
