### ISSUE TITLE
After failure modes SAMPLE_ONLY and SAMPLE_FIRST seem to have no impact

### ISSUE THREAD

**Issue by AFrancani** [jlink/jqwik#148]
With jqwik 1.3.10, I tried using `SAMPLE_ONLY` and `SAMPLE_FIRST` after failure modes at property, test class and configuration level without success.

The property parameters are shrinkable (the property results show a shrunk sample after failure) but, when rerunning it, jqwik runs the previous working tries (using the same seed) before running the failing sample, even though it states `after-failure = SAMPLE_ONLY`.

**Comment by jlink** [comment]
Can you provide a minimal but fully executable example? Thanks.

**Comment by AFrancani** [comment]
While trying to create a minimal executable example, I figured out that the parameters need to be serializable which they aren't in my case but marking them as `Serializable` does not help, though it does in a simpler example.

In any case, I cannot modify the parameter class to make it serializable so I suppose you can consider this issue as closed. But do you have any plan of having a way to replay a specific run in this case? I am asking as otherwise it makes it hard to debug a failing try. I would like to push the adoption of property based testing in my team but I am worried this limitation could jeopardize it.

By the way, thank you for your work on jqwik, it's amazing! :)

**Comment by jlink** [comment]
Yes, they must be Serializable. I have a solution in the back of my mind that would forgo this requirement but this will require a few fundamental changes.

You can always reproduce a run using the random seed and this is the default for failing properties in your IDE. The disadvantage is, however, that all succeeding sample data will be tried first. In the end, however, the exact same failing sample will be executed. What I do in cases like yours is to setup a breakpoint with a condition to pick out the interesting sample data.

**Comment by AFrancani** [comment]
> Yes, they must be Serializable. I have a solution in the back of my mind that would forgo this requirement but this will require a few fundamental changes.

Looking forward to it :)

> You can always reproduce a run using the random seed and this is the default for failing properties in your IDE. The disadvantage is, however, that all succeeding sample data will be tried first. In the end, however, the exact same failing sample will be executed. What I do in cases like yours is to setup a breakpoint with a condition to pick out the interesting sample data.

Good idea, I'll promote this debugging technique, thanks!

**Comment by jlink** [comment]
> Looking forward to it :)

Don't hold your breath. It's probably one major version away, i.e. 1.5.x
