### ISSUE TITLE
Improve Support for Kotlin

### ISSUE THREAD

**Issue by jlink** [jlink/jqwik#151]
## Testing Problem

In principal jqwik can be used with all JVM languages that are able to generate Java compatible classes and annotations. Kotlin is one of those languages and jqwik is a good choice for doing Property-based testing in Kotlin projects. However, not everything looks as nice and polished from Kotlin since jqwik's API is primarily made for Java. Moreover, some useful Kotlin language features are not supported out of the box.

## Suggested Solution

Provide an optional module `jqwik-kotlin` which adds features that simplify and streamline property writing in Kotlin projects. The following things should be supported:

- [x] Make APIs nullsafe where applicable
  - [x] Consider all T of Arbitrary<T> as non-nullable 
  - [x] Arbitrary.orNull -> Arbitrary<T?>
  - [x] Time module API
  - [x] Web module API
- [x] Support nullable Kotlin types to automatically inject nulls
- [x] Combinators.combine(a1, ...).as(...) -> combine(a1, ...) { o1, ... -> }
- [x] Default generation for Kotlin collection types
- [x] Add extension methods to make API more convenient, eg String.any() instead of Arbitraries.strings()
- [x] Operator overloads
  - [x] component1..n for Jqwik tuples 
- [x] Support default generation for types added by Kotlin's standarad library, e.g.
  - [x] Unsigned Integer Types:  Only partially supported
  - [x] Type Aliases
  - [x] IntRange 
  - [x] Sequences
  - [x] Pair, Triple
  - [x] Functions
  - [x] Sealed Classes
  - [x] Inline Classes:  Only partially supported
  - [x] Data Classes
  - [x] Enum Classes 
  - [x] Annotation Classes 
- [x] Support testing of asynchronous Kotlin coroutines
- [x] Property methods in singleton object should use singleton instance as test target
- [x] Quickstart with Kotlin
  - [x] User-guide entry (https://jqwik.net/docs/snapshot/user-guide.html#kotlin-module)
  - [x] Dedicated blog entry (https://johanneslink.net/property-based-testing-in-kotlin/)
- More generators and default generation:
  - CharRange
  - LongRange
  - DoubleRange 
  - Progressions
- ~~Use delegates instead of annotations to declare properties, providers or to change property config parameters~~
- Support kotlin.contracts
- Support generation of types from common K libs:
  - https://arrow-kt.io/
- What else?

## Discussion

Probably something can be learned from Kotest's PBT support: https://kotest.io/docs/proptest/property-test-functions.html

Instead of additional Kotlin support a dedicated `kqwik` could be developped with its own API and only the internal parts shared with jqwik. The disadvantage is much more implementation effort and duplication.

**Comment by jlink** [comment]
To all: Please add comments with more suggestions how a jqwik could support Kotlin in a better way.

**Comment by mmerdes** [comment]
I would favor the kotlin extension over a kqwik alternative.
jqwik can be used for kotlin as is and many companies have both, Java and Kotlin projects.
(let alone mixed java/kotlin projects)
So a uniform API is good.

Adding syntactic sugar for kotlin is, of course, highly welcome as well.

**Comment by mmerdes** [comment]
Informing the generation process from the nullability of kotlin types would be my favourite feature

**Comment by mmerdes** [comment]
Kotlin inline classes might be a special challenge as they are some sort of compile-time wrappers...

**Comment by VitalyArtemiev** [comment]
Might I suggest adding a quick start guide for build.gradle.kts configuration (Kotlin DSL)? For example, the user guide suggests adding 

```
compileTestJava {
    // To enable argument names in reporting and debugging
	options.compilerArgs += '-parameters'
}

```
I've just begun using jqwik, and am unsure of how to do this in my multiplatform project, or what it does even. It might also save new users from dumb mistakes. For example, I've wasted quite a bit of time because of having "test-junit" instead of "test-junit5" as a dependency for one of my source sets, which bricked my old tests without me noticing.

**Comment by jlink** [comment]
Available in 1.6.0-SNAPSHOT

**Comment by jlink** [comment]
Follow-up issue for later releases: https://github.com/jlink/jqwik/issues/250

**Comment by jlink** [comment]
> @VitalyArtemiev You're right. A good starting guide for Kotlin would be essential.
> 

In addition to the [section in the user guide](https://jqwik.net/docs/snapshot/user-guide.html#kotlin-module)
I also wrote an article on [Property-based Testing in Kotlin](https://johanneslink.net/property-based-testing-in-kotlin/).
