### ISSUE TITLE
User-Guide on mobile devices

### ISSUE THREAD

**Issue by zinki97** [jlink/jqwik#152]
User-Guide has not the full width on (all??) mobile devices.

test device: Samsung Galaxy S20+ 5G

Screenshot:
![Screenshot_20210124-174345_Chrome](https://user-images.githubusercontent.com/72615180/105637148-40b4c600-5e6c-11eb-8d07-da95361fd6b2.jpg)

Solution: Provide full width on all mobile devices

**Comment by jlink** [comment]
Do you know the device width?

**Comment by zinki97** [comment]
Device screen: 3.200 x 1.440 px (height x width)
Source: Samsung site

**Comment by jlink** [comment]
Any idea how the media query should look like?

**Comment by zinki97** [comment]
> Any idea how the media query should look like?

Not really. 

A few weeks ago the problem was not present, the problem is new.

**Comment by jlink** [comment]
New browser version on your Samsung? The CSS has not changed for a long time.

**Comment by zinki97** [comment]
> New browser version on your Samsung? The CSS has not changed for a long time.

I don't know. Maybe it has something to do with rearranging the elements?

**Comment by jlink** [comment]
Does it only happen in the user guide? If so in all versions or just the latest?

**Comment by zinki97** [comment]
Yes, only in the user guide and in all versions. While looking for it I saw the following:  

- Up to 1.3.7 the width is larger but not the full width
- Since 1.3.8 the width is even smaller

(Screenshots will follow shortly)

**Comment by jlink** [comment]
You may want to check the Snapshot userguide: https://jqwik.net/docs/snapshot/user-guide.html

The black stripe on the right should be smaller now. But I haven't found all violating html yet.

**Comment by zinki97** [comment]
Yes it's smaller.

![Screenshot_20210127-130922_Chrome](https://user-images.githubusercontent.com/72615180/105989171-041de000-60a1-11eb-8d68-ca9b70770ce2.jpg)

**Comment by jlink** [comment]
It looks ok on my iPhone now. 
@zinki97 Could you check if it is ok on your mobile?

**Comment by zinki97** [comment]
![Screenshot_20210128-113519_Chrome](https://user-images.githubusercontent.com/72615180/106125868-f332a480-615c-11eb-8b5f-ef8354a90360.jpg)

Perfect 👍

**Comment by jlink** [comment]
Fixed and deployed on current snapshot userguide. Will be available for current user guide with release 1.4.0
