### ISSUE TITLE
Arbitrary generation inclusive of specific values

### ISSUE THREAD

**Issue by galderz** [jlink/jqwik#163]
I'm looking around and don't see how I can do the following:

Is it possible to enhance the double generator to make sure certain values are included? I don't see an API in `DoubleArbitrary` to add specific values, such as `NaN`, `POSITIVE_INFINITY`, `NEGATIVE_INFINITY`.

It is true that these edge values could be tested manually, but how do you know if they are, or are not, included already in the ones that are generated when you do `@ForAll double...`? I mean, you would not want to be adding extra tests for things that are already covered.

**Comment by jlink** [comment]
@galderz Thanks for bringing that up!

Probably many (if not most) of the values you are thinking about are already generated by default. Have a look at: https://jqwik.net/docs/current/user-guide.html#generation-of-edge-cases

As for those that values that are not included as edge cases by default, there are a few options:
1. Use data-driven properties: https://jqwik.net/docs/current/user-guide.html#data-driven-properties
2. Use `Arbitraries.oneOf()` or `frequencyOf()` to additionally inject some values that are imporant in your domain
3. Extend the edge cases generated by a given arbitrary using `Arbitrary.edgeCases(EdgeCasesConfiguration config)`.
    Sadly this functionality is not documented yet but will be in version 1.4.0.

**Comment by galderz** [comment]
> Probably many (if not most) of the values you are thinking about are already generated by default.

Hardly any are generated actually, including none of the above. For `Arbitraries.doubles().edgeCases()` it shows:

```
EdgeCases[0.0, 1.0, -1.0, 0.01, -0.01, -1.7976931348623157E308, 1.7976931348623157E308]
```

The last two values are `-Double.MAX_VALUE` and `-DOUBLE.MAX_VALUE`.

Thx for the hints on the options, I'll look into those to enhance my tests.

**Comment by jlink** [comment]
I’d consider NaN and infinities as out of domain for most functions that take a number arg. But an annotation, eg @Infinity, to add those might make sense. What do you think?

**Comment by galderz** [comment]
Not sure about an annotation. I've only just started playing with jqwik ;)

Just being able to add them to the edge cases is enough for me. I'm building master locally to try option 3, because that seems the one most suited for me.

I'm not sure that with option 2 there's a guarantee that all the edge cases that I want to be covered are going to be executed. Option 1 seems more cumbersome here cos I just want to enhance an existing arbitrary selection.

**Comment by jlink** [comment]
Tell me, if you need more hints.

**Comment by galderz** [comment]
Actually, option 3 seems to be avaiable in 1.3.10 already. I tried the following and it seem to work :)

```
    @Provide
    Arbitrary<Double> allDoubles() {
        return Arbitraries.doubles().edgeCases(edgeCasesConfig -> edgeCasesConfig.add(Double.NaN));
    }

    @Property
    boolean allDoubles(@ForAll("allDoubles") double aDouble) {
      ...
    }
```

vielen Dank!

**Comment by jlink** [comment]
> Actually, option 3 seems to be avaiable in 1.3.10 already.

Available yes. Just not documented.

**Comment by galderz** [comment]
Have you considered making `add()` take a vararg? Otherwise you have to write:

```
            edgeCasesConfig.add(Double.NaN);
            edgeCasesConfig.add(Double.MIN_VALUE);
            edgeCasesConfig.add(Double.MIN_NORMAL);
            edgeCasesConfig.add(-Double.MIN_NORMAL);
```

**Comment by jlink** [comment]
> Have you considered making `add()` take a vararg? Otherwise you have to write:

Good idea. Will think about it.

**Comment by galderz** [comment]
I've completed some local testing and these seem to be the additions I had to make to cover all missing edge cases I could think of for doubles:

```
    @Provide
    Arbitrary<Double> allDoubles() {
        // MAX_VALUE and -MAX_VALUE included
        return Arbitraries.doubles().edgeCases(edgeCasesConfig ->
            edgeCasesConfig
                .add(Double.NaN)
                .add(Double.NEGATIVE_INFINITY)
                .add(Double.MIN_VALUE)
                .add(-Double.MIN_VALUE)
                .add(Double.MIN_NORMAL)
                .add(-Double.MIN_NORMAL)
                .add(Double.POSITIVE_INFINITY)
        );
    }
```

I tracked those by converting them to IEEE 754 hex representations.

**Comment by jlink** [comment]
Double.MIN_VALUE and -Double.MIN_VALUE should be included by default. I’ll check which of the others make sense to add as default edge cases.

**Comment by jlink** [comment]
One question that comes up when adding edge cases to doubles or floats: When generating random values the scale (more or less the number of fractional digits) is considered. Values like MIN_VALUE tend to have many more digitals. Should they be rounded to the intended number of digitals?

**Comment by galderz** [comment]
> Double.MIN_VALUE and -Double.MIN_VALUE should be included by default. I’ll check which of the others make sense to add as default edge cases.

See above for my output for `Arbitraries.doubles().edgeCases()`. They didn't show up.

> One question that comes up when adding edge cases to doubles or floats: When generating random values the scale (more or less the number of fractional digits) is considered. Values like MIN_VALUE tend to have many more digitals. Should they be rounded to the intended number of digitals?

Hmmmm, not sure TBH... If I were you I'd look at the rounding rules (e.g. https://en.wikipedia.org/wiki/IEEE_754) and see given a value, what kind of rounding is expected to happen. You could add some values that either side of the rounding rules if you want to add edge values here.

**Comment by jlink** [comment]
After going through the mechanism of how jqwik handles double and float generation I tend to not include +/- MIN_VALUE and +/- MIN_NORMAL as default edge cases. The reason is that internally all decimal numbers are projected onto BigInteger and are then scaled afterwards. That's to say that MIN_VALUE and MIN_NORMAL will almost always be equal to zero. Adding them by default using the same mechanism as you show above would result in those edge cases to be unshrinkable and thus deteriorate shrinking behaviour for most cases, providing value for only few cases.

Thus, I'll close this issue as "won't fix".

If you think it's worthwhile to have something like `Arbitraries.doubles().withSpecialEdgeCases()` and a corresponding annotation to trigger this behaviour, please open a new issue. I'm willing to do that rather soonishly if there is interest.
