### ISSUE TITLE
Performance degradation with 1.4.0

### ISSUE THREAD

**Issue by tmohme** [jlink/jqwik#166]
Using 1.4.0 (as opposed to 1.3.10) we experience a severe performance degradation compared to 1.3.10 for _some_ tests.

The time required to execute (at least some tests) seems to increase super-linear with the number of tries.
According to a first quick glance `edgeCases` are heavily involved.
I'll try to investigate this further and/or come up with a reproducer in the following days.

One of the affected test classes (containing 17 tests) shows the following behavior:

 tries | 1.3.10 | 1.4.0
------|------|------
100 | 2.5s | 4.0s
1000 | 8s | 80s
2000 | 14s | 228s

**Comment by jlink** [comment]
I've also seen a couple of performance issues today - sadly one day after release :-/

@tmohme Can you share one or two examples that make the problem obvious?

**Comment by tmohme** [comment]
I found a strong correlation of slowness with usage of custom Arbitraries for heavy domain objects.
I'll try to provide one of these . . .

**Comment by jlink** [comment]
@tmohme Do you use combinators in you domain arbitraries? That’s what I found at first glance.

**Comment by tmohme** [comment]
Yes, extensively (at least for these heavy domain objects).

**Comment by jlink** [comment]
@tmohme That gives me some guidance where to look.

**Comment by tmohme** [comment]
Will you be OK with a Kotlin example?
There's lots of code involved and converting it to Java would take some time . . .

**Comment by jlink** [comment]
@jlink sure

**Comment by tmohme** [comment]
A small gradle project containing a property-test using an arbitrary-provider for a heavy domain object: 
[jqwik-166.zip](https://github.com/jlink/jqwik/files/5973039/jqwik-166.zip)

**Comment by jlink** [comment]
@tmohme Thanks!

**Comment by jlink** [comment]
@tmohme Can you try "1.4.1-SNAPSHOT"? It should get rid of the performance degredation; as a matter of fact it should speed up generation compared to 1.3.10 quite a bit. Overall test time of jqwik got down by almost 25%.

Here's the downside: The fix completely breaks the behaviour of `Arbitrary.unique()` and the `@Unique` annotation. Both are deprecated anyway but are supposed to stay till 1.5.0. Fixing their behaviour would require a major change in some parts - only to redo everything once they are gone.

It feels like a Catch-22: Either break compatibility despite all the promises I signed with my blood, or leave in the really bad generation performance for composite and flat-map arbitraries, or invest days if not weeks in a deprecated and soon-to-remove functionality.

**Comment by osi** [comment]
@jlink random thought - what if you "faked" the implementation of how `unique` works in 1.4? 

[this](https://gist.github.com/osi/e8eee700652721a51e8a103d171be456) is probably super-naive, but it i wonder if may work "well enough" to bridge until the feature's official removal?

**Comment by jlink** [comment]
@osi That’s actually a good idea. Let’s see what’s possible with limited effort...

**Comment by jlink** [comment]
@osi Turns out, even a "well enough" implementation requires more effort than I'm willing to invest.

I'll go ahead with a 1.5.0 soonish.

**Comment by jlink** [comment]
@tmohme I ran your example with 1.3.10 and 10000 tries: 6.9 sec. With 1.5.0-SNAPSHOT: 6.8 sec. Seems 1.5.0-SNAPSHOT should have fixed your problem.

So I'll probably go for a 1.5.0 release tomorrow.

**Comment by tmohme** [comment]
@jlink I think there is no need to rash this decision to drop backward compatibility so fast:

- I don't know if what _we_ are doing with jqwik is representative or an outlier.
- Everyone who is dissatisfied with 1.4.0 can still use 1.3.10 (as we do for now).
- Also I have no idea how many installations rely on the `unique` behavior (for us the adaption was a very minor thing).
- Although I _guess_ if your adaptions fix the problem with my example, they will probably also fix our other tests, I can't confirm this for sure until I've tried it (tomorrow).

**Comment by tmohme** [comment]
Just ran some timing tests.
Before each set, I ran `mvn test-compile`, then multiple `mvn surefire:test` to get the times for only the actual test execution.
The tests get executed 4-way parallel but not all of the parallel running VMs run for the same duration. The times noted in the table below is for _all_ test to complete, thus dominated by the VM that executed the slowest set of tests.
The cells contain the time to run the tests and the number of tests executed (reported by surefire).

1.3.10        | 1.4.0 | 1.4.1-SNAPSHOT | 1.5.0-SNAPSHOT (855a04ad)
----------|------|------------------|------------ 
1:15 / 479 | 3:52 | 3:12 / 476            | 2:34 / 464
1:18 / 475 | 2:56 | 5:17 / 462            | 2:42 / 456
1:02 / 467 | 4:30 | 4:55 / 468          | 2:41 / 456
1:21 / 456 | 5:19 |                              | 
1:12 / 457 | 4:36 |                              |

I don't have any numbers for executed tests for 1.4.0 because I started the series with 1.4.0 and noticed only after a few runs that the number of executed test vary.  
This variation is unexpected and remarkable in itself and I'll try to find the cause.

**Comment by jlink** [comment]
@tmohme Looks like an interesting riddle :-/ There’s obviously more going on...

**Comment by tmohme** [comment]
I'll try to look a bit broader (with gradle) on our tests find out which tests are affected most.
Maybe I find some commonalities and thus another approach for tackling the regression.
Unfortunately I can't work on the problem without interruption.
@jlink Let me know when you want me to do specific tests / comparisons.

**Comment by jlink** [comment]
@tmohme Take your time. I decided not to rush 1.5.0.

**Comment by tmohme** [comment]
I repeated the timing series from above with gradle and a slightly different source state:

- All time values were taken from gradle's test report. 
- All runs reported 476 tests executed :)
- The first run (per configuration) was `./gradlew clean test`, following runs were `./gradlew test --rerun-tasks`, parallel execution and caching were enabled.

1.3.10 | 1.4.0 | 1.4.1-SNAPSHOT | 1.5.0-SNAPSHOT (855a04a)
------|------|------------------|------------------
1:52   | 6:08 | 6:12 | 3:14
1:53   | 6:15  | 6:02 | 3:24
1:56   | 6:31  | 6:38 | 3:20

Next I'll have have a closer look into 1.5.0-SNAPSHOT.

**Comment by jlink** [comment]
@tmohme My guess it that most of the time is spent creating the generator with edge cases.

**Comment by tmohme** [comment]
Investigating all test durations with gradle I found that the slowest test are (as far as I can see) not structurally different to what I provided as a demo I provided you, although they might be even heavier in terms of "number of combined fields".

Internally caching the arbitraries definitely helps a lot. The test-group from which I derived the demo is even fast with with 1.5.0-SNAPSHOT (~6s) than with 1.3.10 (~8s).
Unfortunately my "problem childs" are still 2.5 times slower (~20s vs. ~8s).

**Comment by tmohme** [comment]
A [cpu flame graph](http://www.brendangregg.com/FlameGraphs/cpuflamegraphs.html) of the first 60s of execution of one of my slow tests (tries=10000) with 1.5.0-SNAPSHOT:

![flamegraph](https://user-images.githubusercontent.com/2261413/108241425-1f35ba00-714c-11eb-927d-a6904467b3e2.png)

I guess the column with the hover-note is where the actual test execution happens.
This in turn means 87.55% of the time jqwik is busy with "ResolvingParametersGenerator.next" (43.96% of parent) or "GenericProperty.extractParams" (43.41% of parent).

**Comment by tmohme** [comment]
The same clipping for 1.3.10:

![flamegraph-1 3 10](https://user-images.githubusercontent.com/2261413/108243306-37a6d400-714e-11eb-8e6a-816884faae4b.png)

Here the relations are very different: "GenericProperty.testPredicate" is active 52.36% of parent's time while "ResolvingParametersGenerator.next" takes up 28.05% and "GenericProperty.extractParams" uses 19.38%.

**Comment by tmohme** [comment]
Apart from the different relations, it is conspicuous that the call stack seems to be quite a bit deeper with 1.5.0-SNAPSHOT, which could (at least partly) be one reason for the shifted relation.

**Comment by jlink** [comment]
@tmohme Thanks for the detailed analysis. One last question: Is execution time still growing in an overlinear way?

**Comment by tmohme** [comment]
No, it seems to be linear with 1.5.0-SNAPSHOT.
My slow test (group) this afternoon:

tries   | duration [s]
------|------------
  250  | 5.8 
  500  | 10.8
1000 | 20
2000 | 39

**Comment by jlink** [comment]
@tmohme You might want to try the latest 1.5.0-SNAPSHOT (make sure you refresh dependencies). Your demo runs twice as fast as with 1.3.10 here.

**Comment by tmohme** [comment]
I can confirm 1.5.0-SNAPSHOT (c00d94535) is way faster than the previously tested versions.
For comparison I added a column to my [comment from two days ago](https://github.com/jlink/jqwik/issues/166#issuecomment-780570304).

The execution time now seems to grow sub-linear, converging to linear. Probably because it starts slow, followed by significantly faster executions due to cache hits.

The cpu profiling confirms that now the time spend for actually executing the test functions dominates the preparation part:

![Bildschirmfoto 2021-02-19 um 09 51 20](https://user-images.githubusercontent.com/2261413/108481820-ef47fd00-7298-11eb-944f-8902f5acf836.png)

**Comment by jlink** [comment]
@tmohme I take it you'd be satisfied with the performance as it is?

**Comment by tmohme** [comment]
That's right 👍

**Comment by jlink** [comment]
Using memoization, the performance looks fine in https://github.com/jlink/jqwik/commit/13e8ed76f1379cf0319873be310b62c1b1056956
