### ISSUE TITLE
Discussion FizzBuzz Example #1 in README - Bad Pattern?

### ISSUE THREAD

**Issue by CppCoderGermany** [jlink/jqwik#17]
## Question - Not a Testing Problem

What is the different between the #1 example code from [README.md](https://github.com/jlink/jqwik/blob/master/docs/README.md) and this lines of code here?
From README:
```java
class FizzBuzzTests {
	@Property
	boolean every_third_element_starts_with_Fizz(@ForAll("divisibleBy3") int i) {
		return fizzBuzz().get(i - 1).startsWith("Fizz");
	}

	@Provide
	Arbitrary<Integer> divisibleBy3() {
		return Arbitraries.integers().between(1, 100).filter(i -> i % 3 == 0);
	}

	private List<String> fizzBuzz() {
		return IntStream.range(1, 100).mapToObj((int i) -> {
			boolean divBy3 = i % 3 == 0;
			boolean divBy5 = i % 5 == 0;

			return divBy3 && divBy5 ? "FizzBuzz"
				: divBy3 ? "Fizz"
				: divBy5 ? "Buzz"
				: String.valueOf(i);
		}).collect(Collectors.toList());
	}
}
```
My Code:
```java
    @Test
    public void fizzBuzz_startsWithFizzEach3thItem_shallBeTrue() {
        List<Integer> integerList = new ArrayList<>();
        IntStream.range(1, 100).filter(i -> i % 3 == 0).forEach(i -> integerList.add(i));
        for (Integer i : integerList) {
            assertTrue("fizzBuzz Index " + (i - 1) + " shall start with \"Fizz\"!",
                    fizzBuzz().get(i - 1).startsWith("Fizz"));
        }
    }

    private List<String> fizzBuzz() {
      // same code from README ...
    }
```
First my code here is very ugly and i will never use some code like that in my projects/at work.
Because assertions inside Loops are an bad pattern.

I don't want to start a sh*t-storm here, but i only want to discuss this with the whole java-users here.

## Suggested Solution

Here is an code that shares more understanding about what the happen in the test.
It's more code to write, but i verfiy that the algorithm works.
It should be enough to Test only the first 15 items, we don't need 100 Items here!

```java
    @Test
    public void fizzBuzz_verifyTheFirst15Items_shallBeEqual() {
        List<String> expected = Arrays.asList(
                "1",
                "2",
                "Fizz",
                "4",
                "Buzz",
                "Fizz",
                "7",
                "8",
                "Fizz",
                "Buzz",
                "11",
                "Fizz",
                "13",
                "14",
                "FizzBuzz"
        );
        // we only verify the first 15 items, because the algorithm is very trivial!
        assertThat("shall contains all items!", fizzBuzz().subList(0, 15),
                          containsAllExpectedItems(expected));
    }

    private <String> Matcher<Iterable<? extends String>> containsAllExpectedItems(
                                List<String> expected) {
        return contains(
                expected.get(0),
                expected.get(1),
                expected.get(2),
                expected.get(3),
                expected.get(4),
                expected.get(5),
                expected.get(6),
                expected.get(7),
                expected.get(8),
                expected.get(9),
                expected.get(10),
                expected.get(11),
                expected.get(12),
                expected.get(13),
                expected.get(14)
        );
    }

    private List<String> fizzBuzz() {
      // same code from README ...
    }
```

## Discussion

Old way:
Junit4/5
Hamcrest Matchers

Avoids misunderstandings.

We have enough libraries with magic behind the scenes.

Is this really need to use a new way?
The reason of my Issue is only misunderstandings about the what happen here behind the scenes.
For Newbies that i want to present code like jqwik's example, will be hard to understand.

I am ready to be convinced.

Maybe the example is not enough for me, but can good for other developers.

**Comment by rkraneis** [comment]
To chime in from the side, @CppCoderGermany, please care to read what [Property-Based Testing](http://jqwik.net/property-based-testing.html) (the link is from the _Home_ area of the main web site) is all about. TL;DR: You want to test general properties of your code that should hold, e.g. if you append two Strings then the length of the resulting String is alway the sum of the lengths of the two input Strings, regardless of which Strings you choose.

**Comment by CppCoderGermany** [comment]
Thanks to @rkraneis for your comment.

I will give it a try.

**Comment by jlink** [comment]
BTW, one of the next main features I will tackle is exhaustive generation of parameters, so that when you specify something like:

`@ForAll @IntRange(min = 1, max = 100) int`

all parameters (or combinations thereof) will be generated - up to a certain limit. That would functionally be equivalent to your code in `fizzBuzz_startsWithFizzEach3thItem_shallBeTrue`.
