### ISSUE TITLE
Strange behavior with Seed in IntelliJ

### ISSUE THREAD

**Issue by tmohme** [jlink/jqwik#185]
## Testing Problem

I want to use `@Property`'s `seed` parameter to make the generated values deterministic.

## Discussion

In general, this works as expected, but recently I noticed a strange behavior when using this feature in IntelliJ:
In a complex test environment, I get one sequence of generated values when _running_ the test and a **different** sequence of generated values when _debugging_ the test. 
Both sequences by themselves are reproducible.

Unfortunately, I was unable to reproduce this behavior with a dedicated small example test.
So I guess everything works fine from jqwik's perspective (meaning with a given seed, the generated values depend **only** on the given seed) and there is some class-loading (or other external) stuff going on that causes the issue, e.g. by effectively using a _different_ pseudo random number generator.

Could you please [dis]prove this hypothesis before I open an issue with IntelliJ?

edit: I'm using jqwik 1.5.1

**Comment by jlink** [comment]
Usually that should not happen. 

A few questions to clarify potential problems:
- How is configuration parameter "jqwik.failures.after.default" set in junit-platform.properties?
- Is there anything special in the property where you observed it like other usage of randomness, dependence on state etc?

**Comment by tmohme** [comment]
`jqwik.failures.after.default=PREVIOUS_SEED`

I don't use any source of randomness or other external state in the test (at least not knowingly) . . . 
. . . but while checking for this, I managed to reproduce the phenomenon with a smaller example.

Digging deeper into it, I must admit that I actually used _some_ kind of deeply hidden randomness / external state.
In an arbitrary I used `Currency.getAvailableCurrencies()` which returns a `Set` that interestingly has different internal ordering depending on the execution mode (which is not obvious, since hash-functions should be stable).
My solution is, to transform the `Set` to a sorted `List` before building an arbitrary from it.

Thanks for you effort!

**Comment by tmohme** [comment]
I stumbled over another phenomenon with "seed" . . . probably user error and/or misunderstanding, but maybe you could clarify this.

Using "seed" works as expected with an ArbitraryProvider like this:
```
    override fun provideFor(
        targetType: TypeUsage,
        subtypeProvider: ArbitraryProvider.SubtypeProvider?,
    ): Set<Arbitrary<Int>> {
        val firstArbitrary = Arbitraries.defaultFor(Int::class.java)
        val secondArbitrary = Arbitraries.defaultFor(Int::class.java)
        val thirdArbitrary = Arbitraries.defaultFor(Int::class.java)
        val fourthArbitrary = Arbitraries.defaultFor(Int::class.java)

        return setOf(
            Arbitraries.oneOf(
                firstArbitrary,
                secondArbitrary,
                thirdArbitrary,
                fourthArbitrary,
            )
        )
    }
```

But when I change the returned value . . .
```
    override fun provideFor(
        targetType: TypeUsage,
        subtypeProvider: ArbitraryProvider.SubtypeProvider?,
    ): Set<Arbitrary<Int>> {
        val firstArbitrary = Arbitraries.defaultFor(Int::class.java)
        val secondArbitrary = Arbitraries.defaultFor(Int::class.java)
        val thirdArbitrary = Arbitraries.defaultFor(Int::class.java)
        val fourthArbitrary = Arbitraries.defaultFor(Int::class.java)

        return setOf(
            firstArbitrary,
            secondArbitrary,
            thirdArbitrary,
            fourthArbitrary,
        )
    }
```
. . . I no longer get a deterministic sequence of values.
Unfortunately the JavaDoc on `provideFor(...)` does not say much about the returned set of arbitraries.
Why is it a set in the first place?

**Comment by jlink** [comment]
It’s a set because a parameterized type, e.g. List<? extends Comparable> can resolve the subtype to any number of Arbitraries. So the returned set is the combination of your intended arbitrary with all subtype providers. OneOf will choose for each generation step. But only one arbitrary in the set will be used for all values within a try. 

That said, the sequence should be deterministic in both cases. I’ll have a look.

**Comment by tmohme** [comment]
I can reproduce it with my actual test case, but not with something simple like the example I posted above.
I'll try harder to isolate it.

**Comment by jlink** [comment]
I rechecked the usage of the the set of arbitraries. There is no _obvious_ reason why the selection would not be deterministic, but I may have missed something. Please let me know when you have a reproducible example.

BTW, I added the following section to the Javadoc of `ArbitraryProvider.provideFor(..)`:
```
For each try a single, randomly chosen element of the set will be used to generate
all objects represented by this arbitrary. This is necessary in order to make
generation of parameterized types stable.
```

Would that have clarified your last question?

**Comment by tmohme** [comment]
Finally found the root cause: It was still the currency code that hit me. 
Even sorting them did not do the trick because the source set contains duplicates for pretty much any single attribute (just not for a "complete" Currency.
Now I hard-coded the list of currencies-to-use with what is available on my DEV machine, knowing that this would break in PROD.
Currently all tests are passing.
We have to re-visit this when we stumble over a test that fails because the currency code provided to it was not actually supported on the test-executing machine. 

As for the JavaDoc change: This is a welcome addition.
So the values generated (within a try) by `Arbitraries.oneOf(...)` might stem from by different arbitraries, while with the Set returned by `provideFor(...)` I always get values from the same arbitrary (within a try)?

**Comment by jlink** [comment]
> As for the JavaDoc change: This is a welcome addition.
> So the values generated (within a try) by `Arbitraries.oneOf(...)` might stem from different arbitraries, while with the Set returned by `provideFor(...)` I always get values from the same arbitrary (within a try)?

Exactly.

**Comment by tmohme** [comment]
Thanks again for your support.
