### ISSUE TITLE
Getting the output of JQWik programmatically

### ISSUE THREAD

**Issue by Jaswar** [jlink/jqwik#209]
## Testing Problem

I am helping in improving software used in course focused on software testing. In the software the students are given two files, one being the source code that needs to be tested, the second being the one where they write their tests. Our software then needs to compile both files, run their tests and run our own tests on which the grading is based.  

In some questions we ask to write property based tests with JQWik. We are currently looking for ways to modify the output of potential error messages - for example if a test fails. In the case of JQWik we would only like to see the assertion error and the inputs that caused the error, something in the lines of:
```
Property test "testValueInArrayUniqueElements" failed:
org.opentest4j.AssertionFailedError: expected: <1> but was: <0>

Inputs that caused the failure:
arg0: [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
arg1: ArrayUtilsTests$InputClass@2f3c6ac4
```

I have successfully managed to show the assertion error with JUnit API in the way specified, however I am unable to get the JQWik message. We don't need to display parts of the error message, eg: the config part.

Ideally we would like to be able to access the output of JQWik programmatically, via the use of some sort of API, without the need to parse the output string to find the information we want. We would also like to avoid changing the students' solutions (for example to add some annotations or methods that would be used by our software).

## Attempted Solutions

I have tried implementing `org.junit.platform.launcher.TestExecutionListener`, especially the `reportingEntryPublished` method, hoping that JQWik would return the error message there, however it seems like that does not happen. I also tried looking into some implementations of this interface, but haven't found a listener that would see the JQWik output.

Furthermore, I have attempted to use `net.jqwik.api.SampleReportingFormat`, however I have not been able to launch it successfully. In particular I would like to ask what is meant by this sentence: _register an implementation of net.jqwik.api.SampleReportingFormat through Java’s java.util.ServiceLoader mechanism._ How exactly should an example `SampleReportingFormat` be registered so that it is used by JQWik?

The current solution is that we capture the traffic to `System.out` and display it after our error messages. Then if there is a property test that fails, the error says to have a look in the raw console output below. With this solution we could also do some pattern matching to extract the information we need, but I believe there should be a simpler solution.

## Discussion

How to access the failed tests output of JQWik via some sort of API? This could be with JUnit listeners, JQWik reporting or any other solution that would not require parsing the raw console output or changing the student's solution.

**Comment by jlink** [comment]
Short answer from the top of my head: You can switch on standard JUnit platform reporting (`TestExecutionListener.reportingEntryPublished(…)`) by using configuration parameter `jqwik.reporting.usejunitplatform = true`. See https://jqwik.net/docs/current/user-guide.html#jqwik-configuration. 
The reason this is switched off by default is that Gradle still doesn’t support it properly after all theses years :-(

As for sample reporting format registration see:
https://github.com/jlink/jqwik/blob/main/documentation/src/test/java/net/jqwik/docs/reporting/SampleReportingExamples.java and https://github.com/jlink/jqwik/blob/main/documentation/src/test/resources/META-INF/services/net.jqwik.api.SampleReportingFormat.

Does that help to lead you in the right direction?
In what way would you like to influence the details of reporting?

**Comment by Jaswar** [comment]
Thank you for your response. 
In general the problem we are facing now is that JQWik returns the error message directly to the console with System.out. I assume the message is built from some objects, we would like to be able to access the objects directly, not via the message. In this way we could select what is or what is not displayed. Could you direct me to the classes/methods that create and display the message? Or is this somehow done with JUnit API?

**Comment by jlink** [comment]
Since you're starting the test run programmatically, the junit-platform configuration file is not evaluated. 
Instead, you have to set parameters programmatically. Something along the lines of

```
LauncherDiscoveryRequest request = LauncherDiscoveryRequestBuilder.request()
      .configurationParameter("jqwik.reporting.usejunitplatform", "true")
      .selectors(selectClass(testClass))
      .build();
```
but I haven't tried it. I also don't think that `SummaryGeneratingListener` remembers the report entries.
You will probably have to build your own listener implementation.

Alternatively, you could go with a jqwik-only solution and register a global around-property hook: https://jqwik.net/docs/current/user-guide.html#aroundcontainerhook. 
The `ContainerLifecycleContext` object you'll hold in your hands has a
`wrapReporter(Function<Reporter, Reporter> wrapper)` method that can be used to intercept any reporting - I think statistical reports are not in there. Mind that this is an experimental feature and may change in future releases.

As for the classes that actually generate the reports, they exist but they are not being exposed.
What parts of the report would be interesting to you, and how would you want to change standard reporting?

**Comment by Jaswar** [comment]
Indeed the `.configurationParameter("jqwik.reporting.usejunitplatform", "true")` works. In the end we decided to go with the full message, but we still needed this to have the message displayed in the correct place. Thank you for your help!
