### ISSUE TITLE
Print jqwik properties info even when tries=1

### ISSUE THREAD

**Issue by apoorva-sriv** [jlink/jqwik#217]
This would help esp. for logging the seed for reproducibility.

**Comment by jlink** [comment]
Since the seed only plays a role if there are `@ForAll` parameters, would it fill your need if reporting only happens if there is at least one forall param?

**Comment by apoorva-sriv** [comment]
@jlink, yes, that would be better actually!

**Comment by jlink** [comment]
Fixed and released in 1.5.5-SNAPSHOT
