### ISSUE TITLE
Bug: `tries = 0` runs 1000 tries instead of 0

### ISSUE THREAD

**Issue by apoorva-sriv** [jlink/jqwik#218]

**Comment by jlink** [comment]
What would you expect that 0 tries does? For disabling a property there’s the `@Disabled` annotation. 

Currently 0 is the default value of `Property.tries() `and will thus use the global tries default which is 1000. It works as designed; you can convince me, however, that a better design exists.

**Comment by apoorva-sriv** [comment]
I expected it to not run any tries (work like `@Disabled` essentially).
