### ISSUE TITLE
Throw exception if `minLength < 0` or `maxLength < minLength`

### ISSUE THREAD

**Issue by apoorva-sriv** [jlink/jqwik#221]
`StringArbitrary`'s `ofMinLength` and `ofMaxLength` seem to work even with negative lengths or when `maxLength < minLength`. Throwing an exception in such cases would be helpful to detect errors earlier and be in line with https://commons.apache.org/proper/commons-text/apidocs/org/apache/commons/text/RandomStringGenerator.html#generate-int-int-.

**Comment by jlink** [comment]
This makes sense. Is on the list for one of the next versions.

**Comment by jlink** [comment]
Fixed in https://github.com/jlink/jqwik/commit/7e7eacdbb586f7299f96c4e03337e1e0fd61d8bf.
Released to 1.5.6-SNAPSHOT.
