### ISSUE TITLE
Change the min defaults of all numeric types from 0 to MIN_VALUE

### ISSUE THREAD

**Issue by apoorva-sriv** [jlink/jqwik#222]
~~`@ForAll` is misleading for numeric types since it does not include the entire range of the number. (It starts from only `0` by default, excluding negative numbers.)~~

Apart from backward compatibility, the only place where this may be an issue is `Double.MIN_VALUE` and `Float.MIN_VALUE` since the default `Scale` of `2` is too small to represent them.

**Comment by jlink** [comment]
Are you saying that a plain `@ForAll int anInt` only generates positive integers? This should not be the case and would be a bug. Can you add a test case so that I can verify?

**Comment by apoorva-sriv** [comment]
My bad. I saw that the [`min() default` of `@IntRange`](https://github.com/jlink/jqwik/blob/main/api/src/main/java/net/jqwik/api/constraints/IntRange.java#L27) was `0` and thought that `@ForAll` would generate only non-negative numbers, but it turns out it does generate negative numbers too.

**Comment by apoorva-sriv** [comment]
However, it would be nice to change the `min() default 0` of `@IntRange`, `@FloatRange`, etc. to `Integer.MIN_VALUE`, `Float.MIN_VALUE`, etc.

**Comment by jlink** [comment]
When designing the annotations API for numbers the use cases I looked at mostly used positive numbers. That’s why `@IntRange(min=0, max = 10)` looked like unnecessary overhead to me. That’s definitely a judgement call and I might decide differently today. Changing it now, however, would break a lot of code; I don’t think that’s justifiable.

**Comment by apoorva-sriv** [comment]
Is there a way to configure it globally then?

**Comment by jlink** [comment]
> Is there a way to configure it globally then?

No, that would be a new feature. 

As a feature it wouldn't make sense to just allow setting of `IntRange.min`. Instead setting of many/most/all defaults might be worthwhile. If you favour s.t. like this, I suggest you create a new issue so that others can vote and join the discussion.

**Comment by jlink** [comment]
Closing and awaiting your new issue about configuring default values.
