### ISSUE TITLE
Do not use ascii as default String character range

### ISSUE THREAD

**Issue by Danny02** [jlink/jqwik#23]
The `DefaultStringArbitrary` class uses `Arbitraries.chars().ascii()` as default character arbitrary.

I think this is very supprising in the least and also makes the method `ascii()` method in `DefaultStringArbitrary` superfluous.

I would recommend to change the default to `Arbitraries.chars().all()`.

At the moment it is not an easy feat to test unicode Strings.

**Comment by jlink** [comment]
You are right.

Fixed in https://github.com/jlink/jqwik/commit/20b353f8df9ea64c4c6f2e7220abf7e279a4daa1
