### ISSUE TITLE
jqwik with JMockit

### ISSUE THREAD

**Issue by SashGraf** [jlink/jqwik#25]
Hi,

I tried to use jqwik with JMockit. In this way:

```java
import static org.junit.jupiter.api.Assertions.assertNotNull;
import org.junit.jupiter.api.Test;
import mockit.Mocked;
import net.jqwik.api.Example;

public class JqikWithJMockit {

@Mocked
public Object object;

@Test
void test() {
	assertNotNull(object);	
}

@Example
boolean whenObjectIsMockedThenItShouldBeNotNull() {
	return object != null;
}
```

The `object `is mocked for the JUnit5 test but `null` for jqwik test. Any idea? Is it possible to use any mock frameworks with jqwik?

Thanks
Sash

**Comment by jlink** [comment]
OK. I eventually found the current documentation:
http://jmockit.github.io/tutorial/Introduction.html#runningTests

I guess the javaagent approach could work with jqwik. Let me know if you try it (successfully or unsuccessfully).

**Comment by jlink** [comment]
I didn't succeed in making it work either. So you'd probably have to ask the author of @jmockit if there is a programmable way of invoking all the necessary mocking harness. Looking at https://github.com/jmockit/jmockit1/blob/master/main/src/mockit/integration/junit5/JMockitExtension.java shows that there is quite a lot going on...

But maybe there is a more straightforward way to solve the testing problem you want to solve with integrating jmockit with jqwik? In my experience, mocking is not often necessary when doing proberty-based testing. In the rare occassions in which I did use it Mockito was fully up to the job. 

So if you like, open an issue describing your _testing problem_ and we can try to find a solution for that.
