### ISSUE TITLE
Container class should inherit @PropertyDefaults

### ISSUE THREAD

**Issue by DirkToewe** [jlink/jqwik#252]
## Testing Problem

Consider the following example:

```java
public class DefaultsTest
{
  @PropertyDefaults( tries = 100_000 )
  abstract class Template
  {
    @Property void test( @ForAll Random rng ) {
      assertThat( rng.nextDouble() ).isBetween(0.0, 1.0);
    }
  }

  @Group class MyGroup extends Template {}
}
```

`MyGroup::test` is called the default number of 1000 tries despite the `@PropertyDefaults` annotation to the `Template`.

## Suggested Solution

If test groups were to inherit `@PropertyDefaults` from extended/implemented classes, that would be quite useful.

## Discussion

If in the above example `DefaultsTest` was annotated with `@PropertyDefaults` as well then it should take precedence over the `Template` defaults. Otherwise it would not be consistent with the current behavior.

**Comment by jlink** [comment]
Thanks for catching that. I hadn’t considered that so far. 

One of the problems I see: As soon as inheritance is considered for PropertyDefaults the diamond problem of multiple inheritance comes into play. What do you think is the best way to handle it?

What should happen if `DefaultTests` had an annotation `@PropertyDefaults(tries=10)`?

**Comment by DirkToewe** [comment]
So what currently what would happen is that `MyGroup::test` is only executed 10 times. Personally, I would try to maintain that behavior (somebody else might rely on it). So defaults of the outer class `DefaultsTest` should override the defaults inherited/extended from `Template`.

A few alternatives that come to mind:
  * throw an error to force the user to add an `PropertyDefaults` to `MyGroup` to resolve the conflict.
  * add a setting to `junit-platform.properties` to specify the default behavior.
  * add a setting to `@Group` to specifiy the behavior. Something like `inheritPropertyDefaults=true`.

**Comment by jlink** [comment]
> So what currently what would happen is that `MyGroup::test` is only executed 10 times. Personally, I would try to maintain that behavior (somebody else might rely on it). So defaults of the outer class `DefaultsTest` should override the defaults inherited/extended from `Template`.
> 

I think that’s reasonable. 

Remains the case where two supertypes eg a class and an interface both have conflicting defaults set. That could produce an error log or even an exception.
I might go with what’s easier implementation-wise.

**Comment by DirkToewe** [comment]
My knowledge of Annotations is very limited, but I believe You can simply add `@Inherited` to the `@PropertyDefaults` annotation and it should automatically inherited.

**Comment by jlink** [comment]
> My knowledge of Annotations is very limited, but I believe You can simply add [`@Inherited`](https://docs.oracle.com/javase/8/docs/api/java/lang/annotation/Inherited.html) to the `@PropertyDefaults` annotation and it should automatically inherited.

That only solves the problem of presence of an annotation, but not the overloading of certain attributes of an annotation.
This will require to crawl the full inheritance graph in one way or the other, I assume.

**Comment by jlink** [comment]
Hopefully fixed in https://github.com/jlink/jqwik/commit/7fcc1abd5f44a85062bab831e4d4abaa554a078a

**Comment by jlink** [comment]
Available in 1.6.1-SNAPSHOT.
@DirkToewe Please test when you find the time.

**Comment by DirkToewe** [comment]
Sorry for the delayed response: Inheritance of `@PropertyDefaults` works now. What's a little curious to me is that `@PropertyDefaults` from interfaces seem to take precedence over the ones from a class. In the following example:

```java
@PropertyDefaults( tries = 1337 )
interface ITemplate {}

@PropertyDefaults( tries = 42 )
abstract class Template
{
  @Property void test( @ForAll int x ) {
    assert Math.abs(x) >= 0 || x == Integer.MIN_VALUE;
  }
}

public class ProDefaultsTest extends Template implements ITemplate
{
}
```

The tests are executed 1337 times as specified by the interface. It is a little unexpected, but not really an issue.

**Comment by jlink** [comment]
> The tests are executed 1337 times as specified by the interface. It is a little unexpected, but not really an issue.

I would have preferred to have a different precedence: Property -> PropertyDefaults in class -> PropertyDefaults in parent class -> PropertyDefaults in interfaces. That would have required, though, to implement an annotation and meta-annotation search through the whole graph of dependencies myself. As it is now I could use stuff from JUnit Platform support. Maybe I was too pragmatic.

**Comment by DirkToewe** [comment]
Pragmatism FTW! I can't really think of a practical example where it would be an issue.
