### ISSUE TITLE
Documentation problem: Broken example

### ISSUE THREAD

**Issue by tmohme** [jlink/jqwik#26]
## Documentation Problem

If I'm not mistaken, the User Guide is wrong in one place. The paragraph "Constraining parameterized types" provides the following example:

```
@Property
void aProperty(@ForAll @Size(min= 1) <@StringLength(max=10) String> listOfStrings) {
}
```

## Suggested Solution

The example should be:

```
@Property
void aProperty(@ForAll @Size(min= 1) List<@StringLength(max=10) String> listOfStrings) {
}
```

## Discussion

Btw.: Thanks for this great piece of software & documentation :)

**Comment by jlink** [comment]
Thanks for the catch!

Fixed in https://github.com/jlink/jqwik/commit/af8a24ccfcff8e7b0124ad4034ce467c3f8e8945
