### ISSUE TITLE
Unable to use with Mockito

### ISSUE THREAD

**Issue by Jiehong** [jlink/jqwik#261]
## Testing Problem

I'm trying to use jqwik with Mockito, but my system under test is null.

Here is an example:

```java
package com.amadeus.maestro.robot.authentications.hosted;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import org.slf4j.Logger;

import net.jqwik.api.ForAll;
import net.jqwik.api.Property;

class Hello {
  private final Logger logger;

  Hello(final Logger logger) {
    this.logger = logger;
  }

  public Object doSomething(final String data) {
    // do something useful
    return data;
  }
}

@ExtendWith(MockitoExtension.class)
public class HelloTest {
  @Mock private Logger logger;
  @InjectMocks private Hello sut;

  @Property
  void testWithRandomData(@ForAll final String data) {
    this.sut.doSomething(data);
  }

  @Test
  void testWithExample() {
    this.sut.doSomething("hand picked");
  }
}
```

If you run those tests, `testWithExample` will pass, but `testWithRandomData` will not run: you'll get a NullPointerException, because `this.sut` is null, so `this.sut.doSomething` fails.

So it seems that the mockito instance is not created for the property, but it's correctly created for the "normal" junit test (`@Test`).

I was unable to find a way to make this work.

Dependencies:

- mockito 4.0.0
- junit 5.8.1

(example of tutorial for both: https://www.baeldung.com/mockito-junit-5-extension)

**Comment by jlink** [comment]
Short answer: `@ExtendWith(MockitoExtension.class)` is a Jupiter engine mechanism. jqwik is a different test engine. Two engines do not combine their life cycles.

Solution 1: Use Mockito without extension, which is quite straightforward.
Solution 2: Write your own Mockito extension for jqwik.

Long answer will follow one of these days...

**Comment by jlink** [comment]
## Solution 1

```java
class HelloTest {
	@Mock private Logger logger;
	@InjectMocks private Hello sut;

	private AutoCloseable mockitoCloseable;

	@BeforeProperty
	void initMocks() {
		mockitoCloseable = MockitoAnnotations.openMocks(this);
	}

	@AfterProperty
	void closeMocks() throws Exception {
		mockitoCloseable.close();
	}

	@Property
	void testWithRandomData(@ForAll final String data) {
		this.sut.doSomething(data);
	}
}
```

**Comment by jlink** [comment]
## Solution 2: Write your own MockitoHook

```java
@AddLifecycleHook(MockitoHook.class)
class HelloTest {
	@Mock private Logger logger;
	@InjectMocks private Hello sut;

	@Property
	void testWithRandomData(@ForAll final String data) {
		this.sut.doSomething(data);
	}
}

class MockitoHook implements AroundPropertyHook {

	@Override
	public PropagationMode propagateTo() {
		return PropagationMode.ALL_DESCENDANTS;
	}

	@Override
	public PropertyExecutionResult aroundProperty(PropertyLifecycleContext context, PropertyExecutor property) throws Throwable {
		AutoCloseable mockitoCloseable = MockitoAnnotations.openMocks(context.testInstance());
		try {
			return property.execute();
		} finally {
			mockitoCloseable.close();
		}
	}
}
```

The `MockitoHook` implementation could be more sophisticated; e.g. you may want to specify if mock objects are being reset per property or per try.

**Comment by jlink** [comment]
One more thing: I personally never mix Jupiter tests and jqwik properties in the same method. It's possible in theory but one is bound to mix up their different lifecycles and get confused about which parts and annotations are valid for which test methods.

**Comment by jlink** [comment]
Closing as answered. Feel free to re-open the issue if anything is unclear.

**Comment by Jiehong** [comment]
@jlink : thank you for the fast and detailed answer.

Perhaps this information could appear in the documentation? (https://jqwik.net/docs/current/user-guide.html)

**Comment by jlink** [comment]
Currently there's nothing about Mockito or other external libraries in the user guide. So this would be a first.

Where would you look in the user guide for such information? What would be your search terms? Imagine that Mockito is just one of many helper libraries that people may want to use with jqwik.

**Comment by Jiehong** [comment]
Perhaps in the "Advanced Topics", under a new section named "integration with other Jupiter Engines"?

I found an old bug about JMocktit (https://github.com/jlink/jqwik/issues/25) that seems similar.

What do you think?

**Comment by jlink** [comment]
> Perhaps in the "Advanced Topics", under a new section named "integration with other Jupiter Engines"?

It's more "Pitfalls of integration" I'm afraid. I openend a new issue to tackle that: https://github.com/jlink/jqwik/issues/262

Feel free to add new points to the list there.

**Comment by jlink** [comment]
> Things changed a bit since nov 2021. The annotation to use on the test container should be : `@AddLifecycleHook(value = MockitoHook.class, propagateTo = PropagationMode.ALL_DESCENDANTS)`
> 

`AddLifecycleHook.propagateTo` is a way to override a hook‘s default propagation. So both ways should be fine. If the old hook implementation doesn’t work, that’s a bug.

**Comment by lmartelli** [comment]
> > Things changed a bit since nov 2021. The annotation to use on the test container should be : `@AddLifecycleHook(value = MockitoHook.class, propagateTo = PropagationMode.ALL_DESCENDANTS)`
> 
> `AddLifecycleHook.propagateTo` is a way to override a hook‘s default propagation. So both ways should be fine. If the old hook implementation doesn’t work, that’s a bug.

My bad. I didn't see that `propagateTo()` was in `LifecycleHook`. I only selected methods from `AroundPropertyHook`when I added the class in IntelliJ :-\
