### ISSUE TITLE
`IllegalArgumentException` when generating parameters: arrays with `@WithNull`

### ISSUE THREAD

**Issue by dvmarcilio** [jlink/jqwik#270]
## Problem

I'm expecting that jqwik (1.6.1) generates booleans or nulls with the code below, but it throws an `IllegalArgumentException`.
It also happens with other types of arrays.

```java
@Property
void test_case(@ForAll @WithNull boolean[] array) {
    // ...
}
```

## Work as expected

```java
@Property
void test_case(@ForAll @WithNull String str) {
    // generates null and non-null String's
}

@Property
void test_case2(@ForAll @WithNull Integer i) {
    // generates null and non-null Integer's
}

@Property
void test_case3(@ForAll @WithNull List<Integer> list) {
    // generates null and non-null List's
}
```

## Workaround

@jlink kindly provided a workaround:

```java
@Property
void test_case(@ForAll("booleansOrNull") boolean[] array) { 
    // ...
}

@Provide
Arbitrary<boolean[]> booleansOrNull() {
   return Arbitraries.of(true, false).array(boolean[].class).injectNull(0.05);
}
```

**Comment by jlink** [comment]
First research suggests that it only happens with primitive arrays. 

I assume that the error occurs when trying to fill null values into a primitive array. Which brings me to a API design question: Should constraint annotations like WithNull apply to the array, the array base type or both? Currently it’s both which then leads to the attempt of filling a primitive array with nulls.

**Comment by dvmarcilio** [comment]
It seems that `@WithNull` only applies to elements in the case of arrays, right?
Correct me if I'm wrong, considering a  `List<Integer>`: 
- to have null elements: `@ForAll List<@WithNull Integer> list`; 
- to have null elements _and_ a null reference (same as `@WithNull` for arrays?) : `@ForAll @WithNull List<@WithNull Integer> list`.

**Comment by jlink** [comment]
Annotations only apply to arrays because there is no syntactic way to differentiate between the array and the array's base type in Java.

The `@UniqueElements` story is more complicated: Once upon a time there was a `@Unique` annotation that would go with the embedded type of a collection, e.g. `List<@Unique>`. When I finally learned that uniqueness _must_ be a property of the collection itself, I had to rework it and came up with `@UniqueElements`. I could introduce `@NullElements` but IMO it would further ruin orthogonality of annotations.  

So I currently lean towards applying annotations only to the array type, but that's a breaking change, so I'm still hesitant.

**Comment by jlink** [comment]
I fixed the generic issue and documented it here: https://jqwik.net/docs/snapshot/user-guide.html#constraining-array-types

This fix is available in 1.6.2-SNAPSHOT and your example should no longer crash.

**Comment by jlink** [comment]
I wonder if now an annotation like `@ConfigureComponentType(Class<? extend ArbitraryConfigurator>)` would be useful, e.g.

```
@Property
void test_case(@ForAll @ConfigureComponentType(WithNullComponent.class) boolean[] array) {
    // ...
}

class WithNullComponent implements ArbitraryConfigurator { ... }
```

`@ConfigureComponentType(WithNullComponent.class)` could now be transformed into a meta annotation `NullElements` as was suggested above.

Counter argument: It's a lot of hassle for a niche use case that can be solved by a provider method as well.

**Comment by dvmarcilio** [comment]
> I fixed the generic issue and documented it here: https://jqwik.net/docs/snapshot/user-guide.html#constraining-array-types

Thanks for the fix.

> The reason is that there was no way to specify if an annotation should be applied the array type, the component type or both.

I think there is a missing _**to**_ in there: _if an annotation should be applied **to** the array type, ..._

**Comment by jlink** [comment]
@dvmarcilio typo fixed
