### ISSUE TITLE
Consider @Operation to declare Actions to avoid boilerplate classes for actions

### ISSUE THREAD

**Issue by vlsi** [jlink/jqwik#288]
## Testing Problem

~ https://jqwik.net/docs/current/user-guide.html#stateful-testing

The issue with the current `Action`-based approach is that it requires declaring a lot of `Action` implementations (one class per each method)

It would be nice to have out-of-the-box test properties for interfaces like `InputStream`, `OutputStream`, `Map`, `List`.
Guava has `ByteSourceTester` with a limited set of pre-defined cases (see https://github.com/google/guava/blob/156694066b5198740a820c6eef723fb86c054343/guava-tests/test/com/google/common/io/ByteSourceTester.java ), however, it would be nice to have a jqwik-driven property that executes various `InputStream` operations and verifies if the outcomes "match" to the outcomes of another implementation (e.g. `ByteArrayInputStream`)

## Suggested Solution

It might work if jqwik could infer the relevant `Action` automatically from the methods.
It might be helpful for "test oracle" approach where the same operations would be called on a "test oracle" instance, so

For instance:

```kotlin
class InputStreamProperty {
    val inputStreamUnderTest;

    @Operation
    fun read(): Int {
        // ...
    }

    @Operation
    fun read(buffer: ByteArray, offset: Int, limit: Int) {
        // ...
    }

    @Operation
    fun mark(readLimit: Int) {
        // ...
    }

    // ...
}
```

jqwik can infer `toString` implementations as `methodName + arguments`.

## Discussion

https://github.com/Kotlin/kotlinx-lincheck (a framework for testing concurrent data structures) has a similar feature known as `sequentialImplementation` where you provide a simpler implementation, and the framework verifies if the sequential (simpler) implementation can yield the same results as the concurrent structure.

Here's a relevant part of the description: https://youtu.be/EW7mkAOErWw?t=2811
Here's a sample usage: https://github.com/Kotlin/kotlinx-lincheck/blob/fda4d46a72b71af8e127ede7ab9429d135829eaf/src/jvm/test/org/jetbrains/kotlinx/lincheck/test/verifier/AllowExtraSuspensionTest.kt#L63-L65 and https://github.com/Kotlin/kotlinx-lincheck/blob/fda4d46a72b71af8e127ede7ab9429d135829eaf/src/jvm/test/org/jetbrains/kotlinx/lincheck/test/verifier/AllowExtraSuspensionTest.kt#L98-L104

**Comment by jlink** [comment]
I think this is related to https://github.com/jlink/jqwik/issues/80 which suggests a syntactically different approach to compare stateful object under tests and model.

**Comment by jlink** [comment]
@vlsi To get a better grasp of what you’re imagining, could you add an example that shows both stateful object, oracle (what I’d call a model) and the property. Feel free to make the object‘s interface a single method. I just fail to bring all parts together in my head and on my own.

**Comment by vlsi** [comment]
#80 might be relevant indeed.

I implemented `InputStream` tests via `jqwik`: https://github.com/pgjdbc/pgjdbc/pull/2389
The current implementation of `BlobInputStream` is buggy, so `jqwik` detects true issues.

My findings so far are:
1. `InputStream` does not have clear semantics (e.g. `read(,.., len=0)` can return `0` and `-1`), so "compare with golden implementation" is not possible
2. Some methods are allowed to do less work than required (e.g. `skip(10)` might skip 5 bytes)
3. jqwik does not depend on assertions, so it is not clear how could `Action<...>` include assertions
4. There are issues with data generation, however, it is probably a topic for another issue

**Comment by vlsi** [comment]
closing in favour of #80
