### ISSUE TITLE
Builders.withBuilder breaks backward compatibility

### ISSUE THREAD

**Issue by acktsap** [jlink/jqwik#295]
## Testing Problem

I found breaking change when replacing `Combinators.withBuilder` with `Builders.withBuilder`. New one works differently on always nullable Arbitrary. It seems `use(..).in(..)` block is never called in the new one.

Combinators.withBuilder

```java
Arbitrary<Integer> nullable = Arbitraries.integers().injectNull(1.0d);

Arbitrary<HashMap<Object, Object>> combined = Combinators.withBuilder(HashMap::new)
    .use(nullable).in((map, value) -> {
        map.put("key", "value");  // always called
        return map;
    })
    .build();

assert combined.sample().get("key").equals("value"); // always success
```

Builders.withBuilder

```java
Arbitrary<Integer> nullable = Arbitraries.integers().injectNull(1.0d);

Arbitrary<HashMap<Object, Object>> combined = Builders.withBuilder(HashMap::new)
    .use(nullable).in((map, value) -> {
        map.put("key", "value");  // never called
        return map;
    })
    .build();

assert combined.sample().get("key").equals("value"); // always fail
```

Is that an intended behavior or just a bug?

**Comment by jlink** [comment]
@acktsap Thanks for the catch. At first glance I think that's a bug, null values should also be usable in builders.

I'll hopefully be able to fix it soon, so that it will go into the upcoming release 1.6.3.

**Comment by jlink** [comment]
Fixed in https://github.com/jlink/jqwik/commit/25e6d9c69757ed046baa3d4ec0c2e108198b5557
