### ISSUE TITLE
Behavior or Arbitraries::create is misleading

### ISSUE THREAD

**Issue by tvelka** [jlink/jqwik#296]
## Problem

The behavior of `Arbitraries::create` is misleading, if not just wrong. In the example blow the property is tried only once and not 10 times as requested. 

````java
public class ExampleQCTest {
    @Property(tries = 10)
    public void test(@ForAll @From("test") int value) {
        // Value should be tried 10 times, not just once.
        Assertions.assertTrue(value >= 1);
    }

    @Provide("test")
    public Arbitrary<Integer> testValue() {
        return Arbitraries.create(() -> Arbitraries.integers()
                                                   .greaterOrEqual(1)
                                                   .sample());
    }
}
````

Output for the test above: 
````
timestamp = 2022-01-26T10:34:38.020689600, ExampleQCTest:test = 
                              |--------------------jqwik--------------------
tries = 1                     | # of calls to property
checks = 1                    | # of not rejected calls
generation = EXHAUSTIVE       | parameters are exhaustively generated
after-failure = PREVIOUS_SEED | use the previous seed
when-fixed-seed = ALLOW       | fixing the random seed is allowed
edge-cases#mode = MIXIN       | edge cases are mixed in
edge-cases#total = 0          | # of all combined edge cases
edge-cases#tried = 0          | # of edge cases tried in current run
seed = -3930724914637379425   | random seed to reproduce generated values
````

## Suggested Solution

Improve the documentation. It states, that 

> The difference to just(Object) is that the value is freshly generated for each try of a property.

That is correct but also misleading, since to achieve that it reduces the number of tries as demonstrated above. I suspect that most people assume (I certainly did), that `Arbitraries::create` behaves like `Stream::generate`, i.e. generates a infinite stream of samples from a supplier, without limiting the number of tries.

## Workaround

If you cannot use the Arbitrary API as intended and *have to use a supplie*r, then just use something like `Arbitraries.longs().map(seed -> /* generate your stuff here */)` instead. Another option is to add a dummy parameter to your test, i.e. 
````java
    @Property(tries = 10)
    public void test(@ForAll @From("test") int value, @ForAll long _ignored_) {
        // ...
    }
````
That also works, because according to the documentation

> For exhaustive shrinking all generated values are supposed to have identical behaviour, i.e. _that means that only one value is generated per combination._

**Comment by jlink** [comment]
@tvelka Thanks for bringing that up. 

Obviously, the documentation did not guide you correctly here. I'll have to thing about it.

What I do not understand, though, is what you are trying to do.
`Arbitraries.create(..)` is for building an arbitrary, not for generating values. The use case you sketch is much simpler to code:

```java
@Provide("test")
public Arbitrary<Integer> testValue() {
    return Arbitraries.integers().greaterOrEqual(1);
}
```

So, I probably, don't get your point at all.

Could you give more information on what you want to achieve?

**Comment by jlink** [comment]
BTW, the effect you are seeing here is described in the javadoc of this method:

> For exhaustive shrinking all generated values are supposed to have identical behaviour,
> i.e. that means that only one value is generated per combination.

jqwik thinks that your arbitrary will generate just a single value, because that's how create() is typically used.
By default, jqwik will do exhaustive generation if the estimated number of all value combinations (here 1) is <= the number of tries. You will see your intended behaviour with:

```java
@Property(tries = 10, , generation = GenerationMode.RANDOMIZED)
```

But, as mentioned above, I currently don't see how 
```java
Arbitraries.create(() -> Arbitraries.integers().greaterOrEqual(1).sample());
```
could be useful at all. Using `sample()` or `sampleStream()` should never be done in a property. It's for usage outside the jqwik lifecycle only. See https://jqwik.net/docs/current/user-guide.html#using-arbitraries-directly

**Comment by tvelka** [comment]
That is just an example I created to demonstrate the behavior of `Arbitraries::create`. The actual sample generation is a lot more complicated and involves randomly chosen parameters whose values depend on each other. 

I probably would have chosen a different approach, but the sample provider and test was created by someone who used JQWik first time and that was basically the solution he came up with (it used a lot more random parameters though). I noticed the low number of tries during the code review and then started my investigation. It took some time to figure out what is going on.

**Comment by jlink** [comment]
> The actual sample generation is a lot more complicated and involves randomly chosen parameters whose values depend on each other.

When generated values depend on each other, the only viable approach is using `Arbitrary.flatMap(..)` or `Combinators.combine(..).flatAs(..)`. All other approaches, like using `sample()` to use generated values in other arbitraries, are not scalable and not shrinkable. The concept of "flat..." may not be easy to grasp but it's necessary for advanced data generation.

**Comment by jlink** [comment]
> used JQWik first time and that was basically the solution he came up with

This is a documentation/learning/teaching problem. `Arbitraries.create(..)` is definitely not built for that purpose.

**Comment by jlink** [comment]
@tvelka Is there anything you'd like to improve in the current description of Arbitraries.create(..):

```java
/**
 * Create an arbitrary that will use a supplier to generate a value.
 * The difference to {@linkplain Arbitraries#just(Object)} is that the value
 * is freshly generated for each try of a property.
 *
 * <p>
 * Mind that within a {@code supplier} you should never use other arbitraries
 * or do anything non-deterministic.
 * </p>
 * 
 * <p>
 * For exhaustive shrinking all generated values are supposed to have identical behaviour,
 * i.e. that means that only one value is generated per combination.
 * </p>
 *
 * @param supplier The supplier use to generate a value
 * @param <T>      The type of values to generate
 * @return a new arbitrary instance
 */
@API(status = MAINTAINED, since = "1.1.1")
public static <T> Arbitrary<T> create(Supplier<T> supplier) {
	return fromGenerators(
		random -> Shrinkable.supplyUnshrinkable(supplier, true),
		max -> ArbitrariesFacade.implementation.exhaustiveCreate(supplier, max),
		maxEdgeCases -> EdgeCases.fromSupplier(() -> Shrinkable.supplyUnshrinkable(supplier, true))
	);
}
```

**Comment by jlink** [comment]
@tvelka Feel free to reopen when you have a suggestion for improvement.

**Comment by tvelka** [comment]
I think this will suffice. Thank you.

**Comment by tvelka** [comment]
Oh, I forgot to mention, that I took the time and rewrote the generators so that it uses the `.flatAs(...)` instead.
