### ISSUE TITLE
Add meaningful toString implementations to Lifecycle context implementations

### ISSUE THREAD

**Issue by vlsi** [jlink/jqwik#297]
## Testing Problem

```kotlin
override fun beforeContainer(context: ContainerLifecycleContext) {
    println("before: $context")
}
```

It prints something like

```
before: net.jqwik.engine.execution.DefaultContainerLifecycleContext@611f075d
```

## Suggested Solution

Implement `DefaultContainerLifecycleContext#toString()` with something like `"LifecycleContext for " + classDescriptor.toString()` 

It would look like

```
ContainerClassDescriptor: [engine:jqwik]/[class:com.acme.test.fuzz.MappingApplyProperties]/[class:com.acme.test.fuzz.MappingApplyProperties$NetstedGroupProperties]
```

`classDescriptor.toString()` is quite verbose (it includes package names for all the classes, including inner groups), and `classDescriptor.getDisplayName()` is too shallow (it does not include information on parents).

I wonder if `ContainerClassDescriptor#toString()` could be adjusted to skip package and outer class names for the parent classes, so the output looks like

```
ContainerClassDescriptor: [engine:jqwik]/[class:com.acme.test.fuzz.MappingApplyProperties]/[NetstedGroupProperties]
```

**Comment by jlink** [comment]
Since the current `toString` representation of test descriptors is based on their `UniqueID` and `UniqueID` is considered to be internal to engines, I'd rather not fuzz with it.

It makes sense though to reveal the required information in the instance of `ContainerLifecycleContext`. So, what information besides the representing class, which is already available through `ContainerLifecycContext.optionalContainerClass()`, would you like to access?

**Comment by vlsi** [comment]
I guess everything is available via test descriptors (they seem to have parents, etc).
The missing bit is `DefaultContainerLifecycleContext#toString` so the object looks understandable to humans in logs and in the debugger.

**Comment by jlink** [comment]
Your understandable might be my shibbleshabble. What should be part of the string in your opinion?

**Comment by vlsi** [comment]
E.g. hierarchical path of the context like in `[engine:jqwik]/[class:com.acme.test.fuzz.MappingApplyProperties]/[NetstedGroupProperties]`, or `engine:jqwik / class:com.acme.test.fuzz.MappingApplyProperties / NetstedGroupProperties`.

**Comment by jlink** [comment]
I'll offer my suggestions in a few days. Stay tuned.

**Comment by jlink** [comment]
I added toString() implementations to common lifecycle context objects. Here's an example:

```java
@Example
void propertyLifecycleDescriptor() {

	PropertyMethodDescriptor engineDescriptor = (PropertyMethodDescriptor) TestDescriptorBuilder.forMethod(
		InnerTests.class, "aProperty", String.class
	).build();
	DefaultPropertyLifecycleContext lifecycleContext = new DefaultPropertyLifecycleContext(
		engineDescriptor,
		new InnerTests(),
		reporter,
		resolveParameter
	);

	Assertions.assertThat(lifecycleContext.toString())
			  .isEqualTo("PropertyLifecycleContext([engine:jqwik]/" +
							 "[class:net.jqwik.engine.execution.lifecycle.LifecycleContextToStringTests]/" +
							 "[class:InnerTests]/" +
							 "[property:aProperty(java.lang.String)]" +
							 ")");
}

```

It's also been deployed to 1.6.4-SNAPSHOT.

@vlsi Does that fit your needs? If not, just reopen the issue.
