### ISSUE TITLE
Add Action.weight so more impactful actions are reduced first during shrink phase

### ISSUE THREAD

**Issue by vlsi** [jlink/jqwik#304]
## Testing Problem

I test a sequence of actions that creates tables in the database.
Some of the actions are fast as they merely update in-memory state, and another actions call the database.

If the sequence of actions fails, I want jqwik to shrink database-related actions first, so it first discovers the minimal set of DB actions to reproduce the failure, and then it could reduce the rest actions.

## Suggested Solution

Add `double Action#getWeight()`, so "try removing actions" shrinker could remove more impactful actions first.

**Comment by vlsi** [comment]
Closing as I need to gather more cases first.
It looks like weighted shirnking does not yield faster shirnking.

So far I have:
input: 33 actions
after shrink: 3 actions

"shrink from bigger weight to lower weight": 36 steps, ~75 seconds
"shrink from lower weight to bigger weight": 26 steps, ~85 seconds
"shrink random actions" (shuffle(new Random(steps.length))): 32 steps, ~45 seconds

**Comment by jlink** [comment]
Your idea might not have helped in this case. I think, however, that finding a _declarative_ way to influence shrinking behaviour, would generally be useful.
