### ISSUE TITLE
Shared random value between providers

### ISSUE THREAD

**Issue by dhoepelman** [jlink/jqwik#309]
## Testing Problem

I have a domain where a lot of providers depend on some shared value, let's say it's the current timestamp.
Currently it's possible to have a fixed value and share this, but not test random different values.

```java
class MyDomain extends DomainContextBase {
  private final Instant NOW = /* ... */

  @Provide
  Arbitrary<Instant> past() {
    return DateTimes.between(Instant.MIN, NOW);
  }

  @Provide
  Arbitrary<Instant> future() {
    return DateTimes.between(NOW, Instant.MAX);
  }
}

@Domain(MyDomain.class)
class MyPropertyTests {
   @Property
   void myProperty(List<@From("past") Instant> pastTimestamps, List<@From("future") Instant> futureTimestamps) {
      // ...
   }
}
```

In this example there are trivial ways to not need this (such as generating 1 list and partitioning), but this is an example of the base case where you have dependencies between providers.

## Suggested Solution

It would be great if there was a way to have a random value from an `Arbitrary`, which is available and shared between multiple other `@Provider`s.

One way I see that could be achieved is by allowing a `@Domain` to be initialized with a number of values from a `Arbitrary`.
This value can be random during normal runs, but should be fixed once a failure is detected and shrinking starts.

## Discussion

There might already be a good way to do this, but I couldn't distill it from the documentation.
Lifecycle hooks seem related to this, but I don't think this use-case can be achieved with them.

**Comment by jlink** [comment]
[This issue](#294) might be related or even the same feature request.

**Comment by jlink** [comment]
The standard solution for this problem is to provide related values in a single collecting object (self-made or some container like Tuple) and use flat mapping to derive generators from the common dependency. That sometimes requires some boilerplating, though.

**Comment by dhoepelman** [comment]
You linked this issue, but I see https://github.com/jlink/jqwik/issues/294 now. That's indeed the same feature request, thanks!

**Comment by jlink** [comment]
> You linked this issue

It’s 2022 and web editors are still a PITA ;-)
