### ISSUE TITLE
Strings include non-character specials

### ISSUE THREAD

**Issue by karsaroth** [jlink/jqwik#32]
## Testing Problem

(Version 0.8.14)
A `@ForAll String` currently generates a wide range of characters, defined by Unicode, however, it can also include the characters in the special code block for Non-characters (e.g: U+FFFF). Although technically part of the spec, these characters should never appear in a (valid) Unicode string. I suspect being able to generate an always valid Unicode string is a more common requirement than being able to generate a sometimes invalid one.

## Suggested Solution

By default do not include non-character code points when generating a `@ForAll String`.

## Discussion

Perhaps from a pure perspective the way the Strings are currently generated is more correct - so an alternative might be to add some sort of filter to exclude these non-characters, similar to the `@CharRange` annotation, or perhaps a constant which defines those usable characters which could be applied to `@CharRange` might also suit, otherwise that set of characters would have to be defined by the tester.

**Comment by jlink** [comment]
Thanks for the suggestion. I’ll have a look at it when back from vacation end of August.

**Comment by jlink** [comment]
I did some research, mainly reading through http://www.unicode.org/faq/private_use.html

Not being a Unicode expert I was wondering if private characters should also be excluded by default?

**Comment by karsaroth** [comment]
Hmm, I'm no expert either. Since the use case for private characters is when code points are prearanged, I'd assume that anyone wishing to use any of them in a test would want to specifiy explicitly which to use. On the other hand, I believe they do count as assigned characters, so they technically shouldn't cause problems for any standard libraries.

**Comment by jlink** [comment]
With https://github.com/jlink/jqwik/commit/15058076594199252cd0f704d2b195b57067c576 string generation will not use Unicode noncharacters or private use characters unless explicitly stated.

You might want to test this in version 0.8.15-SNAPSHOT and reopen the issue if you find any problems.

**Comment by luvarqpp** [comment]
Link to character-sets has been changed. https://jqwik.net/docs/current/user-guide.html#character-sets
