### ISSUE TITLE
API Discussion: New State-dependent Functionality - Single Method vs. Fluent API

### ISSUE THREAD

**Issue by jlink** [jlink/jqwik#320]
From a functionality perspective the revised state-dependent generation has been discussed in https://github.com/jlink/jqwik/issues/134. I'm wondering about the best (i.e. most intuitive API) for providing the functionality.

## Current API

Currently creating an arbitrary for an `ActionChain` looks like this:

```java
Chains.actionChains(
	() -> new MyStore(),
	Tuple.of(3, new StoreAnyValue()),
	Tuple.of(1, new UpdateValue()),
	Tuple.of(1, new RemoveValue())
).withMaxTransformations(30)
```

The first parameter is a supplier for the initial state, the following vararg parameter enumerates a pair of:
- `weight` (for relative frequency when choosing a transforming action
- the transforming action instance, which implements the following interface

```java
interface Action<S> {
	default boolean precondition(S state) {
		return true;
	}
	Arbitrary<Transformer<S>> transformer(S state);
}
```

Here's the implementation for `RemoveValue`:

```java
static class RemoveValue implements Action<MyStore<Integer, String>> {
	@Override
	public boolean precondition(MyStore<Integer, String> store) {
		return !store.isEmpty();
	}

	@Override
	public Arbitrary<Transformer<MyStore<Integer, String>>> transformer(MyStore<Integer, String> state) {
		Arbitrary<Integer> existingKeys = Arbitraries.of(state.keys());
		return existingKeys.map(key -> Transformer.mutate(
			String.format("remove %s", key),
			store -> {
				store.remove(key);
				assertThat(store.get(key)).isNotPresent();
			}
		));
	}
}
```

This is as close as possible as I could get to the interface of the old state-dependent generation feature.

## Alternative: Fluent API

I some (most?) areas jqwik prefers fluent configuration APIs over methods with many parameters. 
A fluent API equivalent to the code above could look similar to:

```java
ActionChain.initializeWith(() -> new MyStore())
                    .withWeight(3)
                         .always()
                         .transform(store -> {
                              ...
                         }
                    .withWeight(1)...
                    .withWeight(1)
                         .when(store -> !store.isEmpty())
                         .transform(state -> {
                     		Arbitrary<Integer> existingKeys = Arbitraries.of(state.keys());
                     		return existingKeys.map(key -> Transformer.mutate(
	                     		String.format("remove %s", key),
                     		        store -> {
	                     		    store.remove(key);
				            assertThat(store.get(key)).isNotPresent();
	                     		}
		                )
                         );
                   .withMaxTransformations(30);
```

There are of course a lot of options to change names, numbers or parameters, order of methods etc.

## Discussion

My personal preferences change from day to day and I'm really not sure how to find a good and intuitive API for more complex cases like the given one.

Any helpful comments and suggestions are welcome. Both concrete ones and general heuristics.

**Comment by kevinb9n** [comment]
I haven't used this library, but I have released a lot of fluent APIs (e.g. in Guice, Guava, Truth, Flogger...). I think the pattern is great, though I like it much more for expressing an intricate _single_ task than I do for lumping many independent tasks together into a single chain (this is, in fact, one of the most apparent differences between Truth and AssertJ).

Since Java 8, classes with *two* abstract methods are kind of the worst. I would add `Action.when().transform()` as a way to create Action instances even if I did nothing else here. (I did this for guava.dev/Converter with a `from` method, for example, though didn't go fluent with it.)

It seems plausible that these Action instances might be reused in multiple contexts, where the weight assigned will have everything to do with the *context*, while the "when" and the "transform" really do go strongly together. If that's right, then you probably wouldn't want to lose the `Action` type itself as the fluent example might suggest.

Can you conceive of potential future enhancements to your framework that would become hard to do in one model or the other?

**Comment by jlink** [comment]
>I like it much more for expressing an intricate single task than I do for lumping many independent tasks together into a single chain

The chunking feels really random here.

> It seems plausible that these Action instances might be reused in multiple contexts, where the weight assigned will have everything to do with the _context_, while the "when" and the "transform" really do go strongly together. If that's right, then you probably wouldn't want to lose the `Action` type itself as the fluent example might suggest.

That's a good argument and the reason why `Action` has these two methods in the first place. Separating the two aspects in a fluent API somehow feels like tearing a useful cohesion apart.

> Can you conceive of potential future enhancements to your framework that would become hard to do in one model or the other?

A fluent API can always (?) adapt by inserting a new configuration step into the chain of commands. That's why it feels to me more robust towards any changes. But that may be due to my limited imagination.

**Comment by dhoepelman** [comment]
Both APIs are defensible. In terms of usability, I would go for the fluent API, since that is easier for people who do not know the API (yet) and for simple cases.

For cases where you want to re-use, or where precondition and transformation are strongly connected, I would keep `Action` as a fallback and make it fully standalone, so include weight. Then the fluent API could be seen as a builder for `Action`.

Something like

```
interface Action<S> {
	default boolean precondition(S state) {
		return true;
	}
	Arbitrary<Transformer<S>> transformer(S state);
        default int weight() {
		return 1;
        }

        // These would be identical to .withWeight and .when from the builder
        default withWeight(int weight) {
		return new ActionWithWeight(this, weight);
        }

	default withPrecondition(Function<S, Boolean> precondition) {
		return new ActionWithPrecondition(this, precondition);
	}
}

private class ActionWithWeight<S> extends Action<S> {
        private final Action<S> parent;
	private final int weight;
        int weight() { return weight; }
        public ActionWithWeight(Action<S> parent) { this.parent = parent; }
        @Override precondition(S state) { return parent.precondition(S); }
	@Override transformer(S state) { return parent.transformer(S); }
}
```

Another thing I would advice is to make `.always()` and `.withWeight(1)` the default, i.e. `.transform(...)` creates an `Action` with the default values, and you modify afterwards:

```
ActionChain.initializeWith(() -> new MyStore())
  .transform(store -> { 1 }) // no further changes, no precondition and weight 1
  .transform(store -> { 2 })
  .withWeight(10) // modifies 2
  .when(...) // modifies 2
```

i.e. `transform` is always your starting point instead of `withWeight0`

**Comment by jlink** [comment]
> Another thing I would advice is to make `.always()` and `.withWeight(1)` the default, i.e. `.transform(...)` creates an `Action` with the default values, and you modify afterwards:

Is "modify afterwards" always the preferred order for you or does it depend on something else?

**Comment by dhoepelman** [comment]
I think it would be good to go from important / required -> least important / optional.

Since `transform` is what this API is about and it doesn't make sense to have an action without it it's a decent starting point for a fluent API. Weight/Precondition can be seen as modifiers to the transformation.

**Comment by jlink** [comment]
> I think it would be good to go from important / required -> least important / optional.

Sounds like a reasonable heuristic. Moreover, this leads to exactly one keyword (`transform`) to start a new action specification.

**Comment by jlink** [comment]
I just experimented a bit with the approaches. One problem with

```java
ActionChain.initializeWith(() -> new MyStore())
  .transform(store -> { 1 }) // no further changes, no precondition and weight 1
  .transform(store -> { 2 })
  .withWeight(10) // modifies 2
  .when(...) // modifies 2
```
 is implementing it in a typesafe manner.  Each of the methods used above (transform, withWeight, when) must return the final type `Arbitrary<ActionChain>`. This means that there are 
- either many different subtypes, each of which representing a state in the underlying state-machine of configuring the resulting arbitrary instance. 
- or a single subtype that has all the methods thereby allowing nonsensical cascades like

```java
ActionChain.initializeWith(() -> new MyStore())
  .when(...)
  .transform(store -> { 1 }) 
  .withWeight(10)
  .when(...) 
  .withWeight(10) 
  .withWeight(10)
  .when(...)
```

But maybe I'm missing a known Java API implementation pattern?

**Comment by jlink** [comment]
Some form of reasonable (?) compromise could be:

```java
ActionChain.initializeWith(() -> new MyStore())
  .addAction(Action.just(store -> 1)) // no further changes, no precondition and weight 1
  .addAction(10, Action.when(store -> store.isEmpty()).just(store -> 2)) // with weight and precondition
  .addAction(5, Action.just(store -> 3)) // with just weight
  .addAction(new Action<MyStore> { ... }) // using a home-grown action implementation
  .withMaxTransformations(50); 
```

**Comment by jlink** [comment]
One more thing: A valid action chain needs at least one action, i.e., at least one `addAction()` statement is required.

**Comment by jlink** [comment]
Thanks for all the input. Moving final discussion back to https://github.com/jlink/jqwik/issues/134

**Comment by vlsi** [comment]
> Some form of reasonable (?) compromise could be:

I looks like a typical builder rather than fluent interface, so adding the final `.build()` might be reasonable:

```
 ActionChain.builder(() -> new MyStore())
  .addAction(Action.just(store -> 1)) // no further changes, no precondition and weight 1
  .addAction(10, Action.when(store -> store.isEmpty()).just(store -> 2)) // with weight and precondition
  .addAction(5, Action.just(store -> 3)) // with just weight
  .addAction(new Action<MyStore> { ... }) // using a home-grown action implementation
  .withMaxTransformations(50)
  .build()
```

It might be that adding `ActionBuilder` would ease discoverability:

```
 ActionChain.builder(() -> new MyStore())
  .addAction(b-> b.just(store-> 1).build()) // no further changes, no precondition and weight 1
  .addAction(10, b -> b.when(store -> store.isEmpty()).just(store -> 2).build()) // with weight and precondition
  .addAction(5, b -> b.just(store -> 3).build()) // with just weight
  .addAction(new Action<MyStore> { ... }) // using a home-grown action implementation
  .withMaxTransformations(50)
  .build()
```
