### ISSUE TITLE
Consider calling state.Action#precondition, state.Action#transformer without reflection

### ISSUE THREAD

**Issue by vlsi** [jlink/jqwik#331]
## Testing Problem

I'm trying the new API from #134, and I see jqwik calls `state.Action` methods via reflection.
It makes it harder to understand the stacktrace.

## Suggested Solution

Call interface methods without reflection.

## Discussion

Is reflection needed there?
I do understand the reflection might help the engine to verify if the class has a non-trivial method implementation, however, I believe calling the method via reflection is both easier to understand, faster, and less prone to errors.

**Comment by vlsi** [comment]
PS. I'm not sure this is an issue, and it looks like [GitHub Discussions](https://docs.github.com/en/discussions) might be better for these types of "issues".

**Comment by jlink** [comment]
Why does the reflective call bother you? It's not called so often that a performance problem is likely.

Reflection is currently necessary to determine if the methods at hand are overridden. The subsequent call of the overridden method could, I assume, be done statically.

**Comment by vlsi** [comment]
> Why does the reflective call bother you? It's not called so often that a performance problem is likely.

Stacktraces become harder to understand.
"find usages" does not show reflective usages.
The code is harder to follow.

>The subsequent call of the overridden method could, I assume, be done statically.

That is exactly my suggestion.

**Comment by jlink** [comment]
> Stacktraces become harder to understand.
> "find usages" does not show reflective usages.

Reasonable argument. 

Since Action will probably be refactored into two separate interfaces, I'll defer until this is done.

**Comment by jlink** [comment]
Has been resolved with the introduction of `Action.Dependent` and `Action.Independent` in https://github.com/jlink/jqwik/commit/85f5f0308b9f5cfb3549606b7d3a7b0a9d30cb74
