### ISSUE TITLE
API: prefer lambdas as the last parameters

### ISSUE THREAD

**Issue by vlsi** [jlink/jqwik#334]
## Testing Problem

APIs, when non-lambda arguments follow lambda, are awkward to use, especially when lambda spans across multiple lines.

For instance:

```java
interface Arbitrary<T> {
Arbitrary<T> filter(Predicate<T> filterPredicate, int maxMisses)
```

Usage:

```kotlin
fun `use attribute field`(multiplicity: MultiplicityFilter = MultiplicityFilter.ANY) =
    arbitraryAttribute().filter({
        multiplicity == MultiplicityFilter.ANY ||
                mapping.run { it.value }.multiple == (multiplicity == MultiplicityFilter.MULTIPLE)
    }, 934).map { attr ->
        action<ColumnScope>(
```

## Suggested Solution

Prefer placing lambdas at the tail of the argument list since lambdas might become multiline.
Lambdas at the end help both Java and Kotlin:
* 934 at the beginning is way easier to notice and relate to the filter rather than `934` at the end
* Kotlin allows moving the trailing lambda outside of parenthesis, so the code could be like `filter(934) { ... }`

**Comment by jlink** [comment]
It's straightforward to do for `Arbitrary.filter` since this is an experimental API. 

Have you stumbled upon more of that in the public API?

**Comment by vlsi** [comment]
I don't remember other methods.

Quick search suggests 

```java
Arbitrary {
	public static <T> Arbitrary<T> recursive(
		Supplier<Arbitrary<T>> base,
		Function<Arbitrary<T>, Arbitrary<T>> recur,
		int depth
	) 

	@API(status = MAINTAINED, since = "1.6.4")
	public static <T> Arbitrary<T> recursive(
		Supplier<Arbitrary<T>> base,
		Function<Arbitrary<T>, Arbitrary<T>> recur,
		int minDepth,
		int maxDepth
	)
```

However, I am not aware of the tools that might recognize this type of issues and produce warnings.

**Comment by jlink** [comment]
Those have two lambdas and they are stable. Maybe a suitable Kotlin extension function would be even better here, e.g.

```kotlin
fun <T> recur(depth: Int, base: () -> Arbitrary<T>, recurrer: Arbitrary<T> -> Arbitrary<T>): Arbitrary<T>
```

What do you think?

**Comment by vlsi** [comment]
It might be better, however, I did not actually use `recursive`, so I can't comment on the usage side of it.

Having Java and Kotlin arguments in a different order does not really help for understanding the API, so it might be just fine to keep `recursive` as is for a while.
