### ISSUE TITLE
Exception while shrinking a BigDecimal within set of values

### ISSUE THREAD

**Issue by gayatrihimthani** [jlink/jqwik#34]
Hello,
I am using jqwik and have written a test that generates a BigDecimal Arbitrary; upon failure, when the data shrinks, there's an exception thrown "Number x outside the allowed range <range>". I understood that its happening because precision becomes 1 for the value while it runs shrinking logic. I have attached some screenshots for reference.

![bigdecimal_notshrinking_exception](https://user-images.githubusercontent.com/25703484/46595343-89a6ac00-caf5-11e8-830d-33884c7df8b7.png)
![bigdecimal_notshrinking_range](https://user-images.githubusercontent.com/25703484/46595345-91fee700-caf5-11e8-90fa-d07204237109.png)
![bigdecimal_notshrinking_precision](https://user-images.githubusercontent.com/25703484/46595348-962b0480-caf5-11e8-8e96-f5c7b547526d.png)

Can you help to fix this?
Thank you!

**Comment by jlink** [comment]
Thanks for the catch! Can you attach code with which I can reproduce the bug? This would help me tremendously since I can then debug myself.

**Comment by gayatrihimthani** [comment]
Actual test case is quite big, below is a smaller simulation of it:

```
	@Property(tries = 10)
	public void testBigDecimal(@ForAll("getNum") double num) {
		assertTrue(num > 5.0);
	}
	
	@Provide
	public Arbitrary<Double> getNum() {
		return Arbitraries.doubles().between(2.4, 4.9);
	}
```

**Comment by jlink** [comment]
Thanks. I’ll have a look at it probably later this week.

**Comment by jlink** [comment]
Just checked your sample property with the latest versions of jqwik (0.8.15 and 0.9.0-SNAPSHOT). Both seem to shrink the value correctly to `3.0` without throwing a JqwikException.

Which version of jqwik are you using? I loosely remember to have fixed a float related shrinking bug in an earlier version...

**Comment by gayatrihimthani** [comment]
Thank you so much for your reply :)
I was using 0.8.12 version earlier; tested with 0.8.15 now and it worked fine. Just a query here, shouldn't the shrunk value be '2.4' as its the min value from the set that doesn't pass the test?

**Comment by jlink** [comment]
I was wondering about the best shrunk value in that case myself. The distance function I use will value less decimal places as "closer" to the best possible value. If you have a compellting argument why 2.4 is the better value and how to calculate a general distance function for decimal numbers that will lead to this result I'd be happy to see that raised in a new issue.
