### ISSUE TITLE
Avoid using Objects#hash(...) as it allocates an array for every call

### ISSUE THREAD

**Issue by vlsi** [jlink/jqwik#347]
## Testing Problem

Jqwik uses `Objects.hash(...)` a lot, mainly in `Tuple#hashCode`.
Unfortunately, OpenJDK can't avoid vararg allocation in `Object.hash` for now.

Here's a sample allocation report from Java Flight Recorder.
Note that one of the top allocations happen in `Memoize` -> `Tuple3#hashCode`.
<img width="940" alt="allocation profile from jqwik test" src="https://user-images.githubusercontent.com/213894/170440836-6ac01c0c-8fdc-4330-9737-ad62e00b27d8.png">

## Suggested Solution

Replace single-argument `Objects#hash(x)` calls with `Objects#hashCode(x)`, replace multi-argument ones with something like (x*31+y)*31+....

**Comment by jlink** [comment]
For my better understanding: Why is the allocation of a small array a problem in your opinion?

**Comment by vlsi** [comment]
It consumes CPU while doing no useful work.

**Comment by jlink** [comment]
> It consumes CPU while doing no useful work.
This can be argued for a lot of code that is "just" used to avoid duplication ;-) 
Is this concrete example more of a problem than other places?

**Comment by vlsi** [comment]
That is top consumer, and there's a trivial fix.
Is there a need to discuss all that?

Even though I agree the excessive calls to hashCode might be caused by bad generator caching or whatever else, I see absolutely no reason to deliberately use bad-performing code in Tuple implementation when faster alternatives are trivial to implement and maintain (IDEA - generate hashcode)

**Comment by jlink** [comment]
Replacing JDK code with home-made code is worth discussing IMO. Especially since it’s used in so many places.

**Comment by jlink** [comment]
Fixed and released in 1.7.0-SNAPSHOT
