### ISSUE TITLE
Randomize CI matrix

### ISSUE THREAD

**Issue by vlsi** [jlink/jqwik#350]
## Testing Problem

It would be nice to ensure Jqwik is buildable and workable with various OS, JDS, timezone, etc, settings.

## Suggested Solution

For example, the automatic matrix captures locale-dependent issues like https://github.com/spockframework/spock/issues/1414
See how the matrix looks in the fork: https://github.com/vlsi/selenide/actions/runs/1704145433
    
The idea is that you declare test axis like `os`, `java`, `java_distribution`, `timezone`, `locale`, etc, and `matrix.js` produces several jobs for you.

See https://github.com/vlsi/github-actions-random-matrix

The PR could be similar to https://github.com/selenide/selenide/pull/1696

WDYT?

**Comment by jlink** [comment]
I'd rather prefer a fixed matrix over randomization. That said, a matrix with many values uses a lot of resources without a lot of value for the world. 4 builds are already a lot for a rather unimportant project like jqwik.

Are there any variations where you'd expect a high chance of failure?

**Comment by vlsi** [comment]
>4 builds are already a lot for a rather unimportant project like jqwik.

That is exactly my point.
You have 4 jobs, and I see that you miss:
a) Windows, macOS. In my experience, Windows is slightly different (e.g. LF vs CRLF)
b) Timezone: testing with non-default timezones might uncover issues with date arithmetic
c) Different locales. tr_TR is known to cause many issues thanks to dotless `i`
d) Different JDK vendors. For instance, OpenJ9 has a different JIT implementation
e) Special mode where JIT randomizes the generated code. It would 
f) Special mode when "Object#hashCode always returns 1"
etc.

What I suggest is to enumerate the set of desired options, and ask "ci matrix generator" to produce the desired number of CI jobs.
For instance, you could have 4 jobs for PR, and you might want 7 jobs for `main` branch commits.

---

Here's the randomized matrix at work: https://github.com/cbeust/testng/actions/runs/2369197836
I believe it provides the best of the two: it does eventually test edge cases, and it allows a trivial way to limit CI duration by selecting the number of CI jobs.

**Comment by jlink** [comment]
Having thought a bit about it I still stand with a non-randomized build. At least for the time being.

The points you bring above about potential problems are valid. I don't think, however, that using precious resources to raise the probability of detecting them, is worth it in the case of jqwik.

What I think would be effective for many of the variations is to use the latest Maven release and just run the tests (or a subset of them) on potentially randomized setups. Doing that in a rather slow cadence, like once per week, would also keep resource usage reasonably low, I hope. But that's a different kind of project than what you suggest here, so I close this one.

**Comment by jlink** [comment]
@vlsi Do you have mind and time to create a PR with a randomized matrix, but Java 8 and 18 as fixpoints that should always be run?
