### ISSUE TITLE
ContainerGenerator#next might yield different results for the same seed due to state in noDuplicatesHadToBeSwitchedOff

### ISSUE THREAD

**Issue by vlsi** [jlink/jqwik#354]
## Testing Problem

I think `Generator#next` should yield the same results when given the same `Random` inputs.
Unfortunately, `Generator#next` might flip the generation algorithm and reuse it for the subsequent executions, so the generated value depends on both `input random` (which is expected), and `past history of executions` (which is not expected)

I do not know what are the consequences, however, I think non-reproducibility makes shrinking worse.

## Suggested Solution

Avoid stateful flip of the generation algorithm.

For instance:
a) Temporary remove `boolean noDuplicatesHadToBeSwitchedOff` and the relevant code that flips `sizeGenerator`
b) Try querying size estimations from the downstream generator

**Comment by jlink** [comment]
`RandomGenerator.next(Random)` is not guaranteed to always provide the same element when given the same random. Providing uniqueness is one of those cases where it won't. There are others, e.g. when using `Arbitrary.injectDuplicates(..)`.

An invariant that should hold is that any freshly generated generator through `Arbitrary.generator(tries)` will generate the same sequence of values when given the same sequence of randoms. That's not an issue here, I think; although it is in [other cases](https://github.com/jlink/jqwik/issues/340).

I also don't think that shrinking is negatively impacted here, since shrinking hardly ever (except for some flat mapping cases) uses random generation.

**Comment by vlsi** [comment]
non-reproducibility does impact me.

I generate `state.Action` implementations as following:

```kotlin
    fun act(body: context(MappingState) () -> Arbitrary<out ActionWithReceiver<MappingState>>) =
        object : Action<MappingState> {
            override fun precondition(state: MappingState): Boolean {
                val transformer: Arbitrary<Transformer<MappingState>>
                return try {
                    transformer = transformer(state)
                    transformer.sampleStream().map { true }.findAny().isPresent
                } catch (e: NotFoundException) {
                    false
                } catch (e: TooManyFilterMissesException) {
                    false
                }
            }

            @Suppress("UNCHECKED_CAST")
            override fun transformer(state: MappingState) =
                body(state).ignoreException(NotFoundException::class.java)
                    .filter(997) { it.precondition(state) }
                        as Arbitrary<Transformer<MappingState>>
        }
```

In other words, in `Action.precondition` I double-check that arbitrary is able to generate at least one item.
However, since the current generation is non-reproducible, I end up with cases when "precondition was positive" and then jqwik fails to generate a value.

**Comment by vlsi** [comment]
> Providing uniqueness is one of those cases where it won't

Is there an API that makes `Arbitrary` to produce "only unique elements"?
I do not see such an API. `Arbitrary#unique`, and `Arbitrary#distinct` are missing.
`Arbitrary.set()` is not impacted, as it does not require global state.

>Arbitrary.injectDuplicates(..).

It is indeed a problem, however, if you suggest that every generator must be "freshly generated generator", then it means caching can't be used for generators, which would imply poor performance since many default generators are expensive to create (e.g. int range generator goes through BigIntegers for range check)

I wonder if `InjectDuplicatesGenerator` is the only generator that is stateful and relatively hard to convert into a stateless one.

**Comment by jlink** [comment]
`Arbitrary#unique` existed in previous versions. It just turned out that I could not make shrinking work with it. That's why now only collections support uniqueness-related behaviour.

**Comment by jlink** [comment]
What doesn't work in your example, and what I think will never work in jqwik as far as I can see, is to mix values provided by jqwik and using arbitraries directly through `arbitrary.sample()` or `arbitrary.sampleStream()`. There's just too much going on under the hood. At least there's no easy fix.

I guess I'd have to understand `MappingState` and the possible actions to come up with an alternative suggestion of how to achieve what you want to achieve.

**Comment by vlsi** [comment]
What if `injectDuplicates` is replaced with something like `.list(duplicateProbability=...)`? Then it could be stateless

**Comment by vlsi** [comment]
> mix values provided by jqwik and using arbitraries directly through arbitrary.sample() or arbitrary.sampleStream().

I do not think I mix them.
What I want is I want to double-check if the arbitrary is able to produce at least one `Transformer`. I do not use the generated sample value in any way.

**Comment by jlink** [comment]
> It is indeed a problem, however, if you suggest that every generator must be "freshly generated generator", then it means caching can't be used for generators, which would imply poor performance since many default generators are expensive to create (e.g. int range generator goes through BigIntegers for range check)

Caching can be done on a per property basis as long as one makes sure that subsequent calls don't break a generator's invariants. That's why `InjectDuplicatesGenerator` does not store values but only the seed used to generate the values.

**Comment by jlink** [comment]
> I do not think I mix them.
> What I want is I want to double-check if the arbitrary is able to produce at least one `Transformer`. I do not use the generated sample value in any way.

Well, `sampleStream` will use `SourceOfRandomness.current()` under the hood, which is not guaranteed to be the same during shrinking. So the result of filtering is non-deterministic.

**Comment by vlsi** [comment]
> Caching can be done on a per property basis as long as one makes sure that subsequent calls don't break a generator's invariants

I do not say caching is impossible, however, if you expect that every RangomGenerator is stateful, then you can never cache it.
Of course, if you add metadata somewhere (e.g. `Arbitrary#isGeneratorStateful()`), then you know which generators are cacheable, and which are not.
On the other hand, if all the generators are stateless (most of the generators are stateless), then they can be cacheable.

----

>Well, sampleStream will use SourceOfRandomness.current() under the hood, which is not guaranteed to be the same during shrinking. So the result of filtering is non-deterministic

That is true. However, it looks like changes like https://github.com/jlink/jqwik/pull/348 and removal `noDuplicatesHadToBeSwitchedOff` fixed the issues for me. I am not that sure, however, the saddest thing was that re-running jqwik with the same seed did not reproduce the failure. It runs for a while, and then the test fails, and I can't reliably reproduce and retest since, well, the crash is different every time. That is why I keep looking for ways to make jqwik generators stable. By the way, I did have `transformer.generator(1000, true).next(..).value()` in mind as an alternative option to avoid interference with `SourceOfRandomness.current()`

**Comment by jlink** [comment]
An ˋisGeneratorStateful()ˋ property is not required, at least not with the current memoization, implementing ˋequals()ˋ adequately should suffice.

**Comment by vlsi** [comment]
> implementing ˋequals()ˋ adequately should suffice.

That is fair, however, that mixes semantics (you tie "equality" to the "stateful vs stateless generator" property).
Then, having a different method might help to avoid caching the value in the first place (save lookup to `Store....`, `Tuple`, etc).

**Comment by jlink** [comment]
> > implementing ˋequals()ˋ adequately should suffice.
> 
> That is fair, however, that mixes semantics (you tie "equality" to the "stateful vs stateless generator" property). Then, having a different method might help to avoid caching the value in the first place (save lookup to `Store....`, `Tuple`, etc).

I'm hesitant about introducing yet another internal interface method for optimization purposes but it might be the best solution.

As for getting to reproducible generations with the same seed, I also think it's beneficial but your suggested change has the drawback you describe [in your commit](https://github.com/vlsi/jqwik/commit/33553e542a7318df3461b3b08c8f4bab2ce41587):

> The solution for now is to keep using the same size generator no matter what was the previous execution history.
> This might make generation speed suboptimal when the users provides bad bounds for minSize and maxSize.

That's not acceptable since I've hit this scenario quite a few times. I'll ponder other options to get to reproducibility...

**Comment by vlsi** [comment]
>That's not acceptable since I've hit this scenario quite a few times. I'll ponder other options to get to reproducibility...

I believe there's a reasonable workaround: the user could adjust `ofMinSize` and `ofMaxSize` accordingly.

**Comment by jlink** [comment]
> I believe there's a reasonable workaround: the user could adjust `ofMinSize` and `ofMaxSize` accordingly.

The problem only occurs because _jqwik_ chooses to generate collections without duplicates with a higher probability. It's not the user's fault that, e.g., `Arbitraries.integers().between(1, 3).list().ofMaxSize(10)` does not have unique lists longer than 3. That's why I think this problem cannot be unloaded onto the user.

**Comment by jlink** [comment]
I more or less went with your suggestion; additionally, I added a check for the maximum unique elements to make the number of cases where a repeated fail will slow down generation less probable.

Has been deployed to "1.7.0-SNAPSHOT"

Optimizing memoization remains an open issue.
