### ISSUE TITLE
Add import order to .editorconfig for automatic import order setup in IDEA

### ISSUE THREAD

**Issue by vlsi** [jlink/jqwik#355]
Import order could be specified via `.editorconfig` like in https://github.com/pgjdbc/pgjdbc/blob/627702aefef1352baa376ea0e3201fc39946546b/.editorconfig#L27-L30

```editorconfig
[*.java]
# Doc: https://youtrack.jetbrains.com/issue/IDEA-170643#focus=streamItem-27-3708697.0-0
# $ means "static"
ij_java_imports_layout = $*,|,org.postgresql.**,|,*,|,java.**,|,javax.**
```

Doc: https://youtrack.jetbrains.com/issue/IDEA-170643#focus=streamItem-27-3708697.0-0

----

Frankly speaking, it is the first time I see a project that goes for "mandatory star import", and it looks like star import might cause slow compilation times. For instance, `import static net.jqwik.engine.support.JqwikCollectors.*;` caused 10-15 minutes for `compileTestJava`

**Comment by jlink** [comment]
The following line in .editorconfig for quite some time:

`ij_java_imports_layout = javax.**,java.**,|,*,|,net.jqwik.**,|,$*,|,$net.jqwik.**
`

Maybe you're running into the problem that IntelliJ sometimes takes a long time to pick up changes in `.editorconfig` when you switch between projects.

> Frankly speaking, it is the first time I see a project that goes for "mandatory star import", and it looks like star import might cause slow compilation times. For instance, import static net.jqwik.engine.support.JqwikCollectors.*; caused 10-15 minutes for compileTestJava

I prefer the star import style a lot. Most of the time the import block is collapsed in my editor anyway but _when_ I want to look at it, dozens or more lines of imports are just dreadful to my eyes. Might be a personal issue, sorry for that.

I did a few experiments and switched from everything with star to everything without star in `api` and `engine` modules. Compile and build times did not change when running `gradle clean engine:compileJava` or `gradle clean engine:build` or ``gradle clean engine:test`. Can you specify where `import static net.jqwik.engine.support.JqwikCollectors.*;` resulted in the 10-15 minutes of compilation? Could `police-man/forbidden-apis` be the culprit?

**Comment by vlsi** [comment]
I must have missed ij_java_imports_layout, so the suggestion has already been implemented.

**Comment by vlsi** [comment]
>Could police-man/forbidden-apis be the culprit?

I am sure, forbidden-apis could not be the issue there.
I am sure `compileJava` or `compileTestJava` was slow in my case, and `forbidden-apis` examines class files after they are generated by the compiler.

>Can you specify where import static net.jqwik.engine.support.JqwikCollectors.*; resulted in the 10-15 minutes of compilation?

Let me see if the issue reproduces and reconsider.

Another possibility is the slowness might be caused by the static import of `toLinkedHashSet` rather than non-static `JqwikCollectors.toLinkedHashSet`.
