### ISSUE TITLE
setup test selection by means of tagging with gradle / intellij

### ISSUE THREAD

**Issue by 3nigm4** [jlink/jqwik#36]
Please help me setup test selection through tagging. I use intellij community 2018.2.5 and gradle 4.8. The jqwik user guide directs me to gradle/junit5 and intellij sites, but none of these solutions work for me.

I have a basic build.gradle:
```gradle
buildscript {
    dependencies {
        classpath 'org.junit.platform:junit-platform-gradle-plugin:1.1.1'
    }
}

plugins {
    id 'java'
}

group 'diamond'
version '1.0-SNAPSHOT'

sourceCompatibility = 1.8

apply plugin: 'org.junit.platform.gradle.plugin'

repositories {
    mavenCentral()
}

ext.junitPlatformVersion = '1.3.1'
ext.junitJupiterVersion = '5.3.1'

ext.jqwikVersion = '0.9.1'

junitPlatform {
    filters {
        includeClassNamePattern '.*Test'
        includeClassNamePattern '.*Tests'
        includeClassNamePattern '.*Properties'
    }
    // Only enable if you also want to run tests outside the junit platform runner:
    enableStandardTestTask false
}

dependencies {
    testCompile("org.junit.platform:junit-platform-launcher:${junitPlatformVersion}")
    testCompile "net.jqwik:jqwik:${jqwikVersion}"
    testCompile("org.assertj:assertj-core:3.9.1")
}
```
and I want to create a "skip" tag like this: 
```java
    @Example
    @Tag("skip")
    public boolean Example_jqwik_is_cool()
    {
        return true;
    }
```
Adding a test {} block to gradle did not work and also the menue entry shown in the intellij link is not available as of intellij community 2018.2.5, how can I make this work? Thank you!

**Comment by jlink** [comment]
Thanks for pointing that out. I forgot to update this section in the user guide.
Have a look at the updated version:
https://jqwik.net/user-guide.html#using-gradles-built-in-support

Most important point: Don't use the old plugin anymore but use Gradle's built-in support.
You'll probably also change to the latest Gradle version (10.2).

Another trap you might fall into: The `@Tag` you'll have to use with jqwik is
`net.jqwik.api.Tag` and not `org.junit.jupiter.api.Tag`. I know that's confusing but annotation interpretation must be done by the engines themselves, so I was forced to introduce my own annotation class for the same purpose.

Hope that helps.

**Comment by jlink** [comment]
Clarification seems to have been sufficient.

**Comment by jlink** [comment]
No worries.
