### ISSUE TITLE
Consider removing rendered docs from main branch and from the history

### ISSUE THREAD

**Issue by vlsi** [jlink/jqwik#370]
## Testing Problem

Currently, jqwik working directory consumes ~200M for `docs/` by javadocs of all the versions.
It would be nice if the generated documentation could be removed from the git repository (and from the history) so checkout is faster, and it would not consume space on the developers' machines.

If you really want to keep the generated javadoc for all the revisions in git, it would be nice if you could use a different branch for that.

```
 250M └─┬ .
 208M   ├─┬ docs
 208M   │ └─┬ docs
 8.7M   │   ├─┬ snapshot
 6.7M   │   │ └── javadoc
 8.7M   │   ├─┬ 1.6.5
 6.7M   │   │ └── javadoc
 8.7M   │   ├─┬ 1.6.4
 6.7M   │   │ └── javadoc
 8.7M   │   ├─┬ 1.6.3
 6.7M   │   │ └── javadoc
 8.5M   │   ├─┬ 1.6.2
 6.6M   │   │ └── javadoc
 8.5M   │   ├─┬ 1.6.1
 6.6M   │   │ └── javadoc
 8.2M   │   ├─┬ 1.6.0
 6.5M   │   │ └── javadoc
 6.6M   │   ├─┬ 1.5.6
 6.4M   │   │ └── javadoc
 6.6M   │   ├─┬ 1.5.5
 6.4M   │   │ └── javadoc
 6.5M   │   ├─┬ 1.5.4
 6.3M   │   │ └── javadoc
 6.4M   │   ├─┬ 1.5.3
 6.2M   │   │ └── javadoc
 6.4M   │   ├─┬ 1.5.2
 6.2M   │   │ └── javadoc
 6.3M   │   ├─┬ 1.5.1
 6.1M   │   │ └── javadoc
 6.1M   │   ├─┬ 1.4.0
 5.9M   │   │ └── javadoc
 6.1M   │   ├─┬ 1.5.0
 5.9M   │   │ └── javadoc
 5.5M   │   └── 1.3.10
  28M   ├─┬ .git
  26M   │ └─┬ objects
  26M   │   └─┬ pack
  24M   │     └── pack-24507e63c1ea3b1608daee1d8474276987cb8acc.pack
 6.0M   └── engine
```

Removal of `javadoc` and `kdoc` folders yields the following.

```
java -jar bfg-v1.14.0-vlsi-8885d69.jar --delete-folders javadoc --no-blob-protection
java -jar bfg-v1.14.0-vlsi-8885d69.jar --delete-folders kdoc --no-blob-protection
git reset --hard
git gc --aggressive --force
```

```
  31M └─┬ .
  16M   ├─┬ .git
  15M   │ └─┬ objects
  15M   │   └─┬ pack
  12M   │     ├── pack-d4da7709e69cddf0202d25778d5226ce9771db46.pack
 2.8M   │     └── pack-d4da7709e69cddf0202d25778d5226ce9771db46.idx
 7.1M   ├─┬ docs
 6.9M   │ └── docs
 3.3M   ├─┬ engine
 3.3M   │ └─┬ src
 1.8M   │   ├─┬ main
 1.7M   │   │ └─┬ java
 1.7M   │   │   └─┬ net
 1.7M   │   │     └─┬ jqwik
 1.7M   │   │       └─┬ engine
 776K   │   │         └── properties
 1.5M   │   └─┬ test
 1.5M   │     └─┬ java
 1.3M   │       └─┬ net
 1.3M   │         └─┬ jqwik
 824K   │           ├── engine
 520K   │           └── api
 1.4M   ├─┬ time
 1.4M   │ └─┬ src
 900K   │   ├─┬ test
 900K   │   │ └─┬ java
 900K   │   │   └─┬ net
 900K   │   │     └─┬ jqwik
 900K   │   │       └─┬ time
 900K   │   │         └── api
 524K   │   └── main
 888K   ├─┬ api
 884K   │ └─┬ src
 884K   │   └─┬ main
 880K   │     └─┬ java
 880K   │       └─┬ net
 880K   │         └─┬ jqwik
 880K   │           └── api
 744K   ├─┬ documentation
 736K   │ └── src
 664K   └── buildSrc
```

**Comment by jlink** [comment]
Would definitely be an improvement. Thinking about using a dedicated repo and a git submodule in a first step.

**Comment by vlsi** [comment]
I'm not sure what would be the use of submodule then. Moving the full documentation (generated documentation for all the versions) to a different repository might be a nice idea though.

**Comment by jlink** [comment]
> I'm not sure what would be the use of submodule then. Moving the full documentation (generated documentation for all the versions) to a different repository might be a nice idea though.

The submodule will allow keeping the documentation publishing as is: First generate it through Gradle, then copy it to the docs directory (which is a sub-module).

**Comment by jlink** [comment]
Some experimentation showed that a submodule will make some handling more difficult so I just move all rendered docs to a different repo (currently private).

**Comment by jlink** [comment]
Is there any advantage in having the website repo public?

**Comment by vlsi** [comment]
See https://github.com/pricing#compare-features

Pages for private repository requires a paid plan.

**Comment by vlsi** [comment]
> submodule

I worked with submodules multiple times, and I incline they are rarely a good idea.

For the documentation, it looks like a separate repo with pages would work ok

**Comment by jlink** [comment]
> See https://github.com/pricing#compare-features
> 
> Pages for private repository requires a paid plan.

I already moved it to a private repo, so the question is should I make this repo public?

**Comment by vlsi** [comment]
If private works for you, then it is fine. I've no idea what would be the pros and cons of making the pages repository private.
