### ISSUE TITLE
Ability to access seed from code

### ISSUE THREAD

**Issue by stanislavkozlovski** [jlink/jqwik#375]
If a test times out due to bad design (e.g the code loops forever), a CI where it runs may close due to a general timeout and never run the code that prints the seed.

Is there a way to access the seed from the code so that a test can proactively print it out when starting?

**Comment by jlink** [comment]
You can do that by implementing `AroundPropertyHook`, which gives you access to `PropertyLifecycleContext.attributes().seed()`. This section in the user guide provides some introduction to hooks: https://jqwik.net/docs/current/user-guide.html#lifecycle-hooks

**Comment by jlink** [comment]
I assume my answer was sufficient, so I close the issue. 
Feel free to re-open.
