### ISSUE TITLE
Provider from domain context cannot be referenced by name

### ISSUE THREAD

**Issue by lmartelli** [jlink/jqwik#406]
## Testing Problem

```kotlin
import io.kotest.matchers.string.shouldNotHaveLength
import net.jqwik.api.ForAll
import net.jqwik.api.Property
import net.jqwik.api.Provide
import net.jqwik.api.domains.Domain
import net.jqwik.api.domains.DomainContextBase
import net.jqwik.kotlin.api.any

@Domain(MyDomain::class)
class BugTest {
    @Property
    fun fail(@ForAll("customerIds") s: String) {
        s shouldNotHaveLength 0
    }
}

class MyDomain : DomainContextBase() {
    @Provide
    fun customerIds() = String.any().ofMinLength(1)
}
```

Gives `net.jqwik.api.CannotFindArbitraryException: Cannot find an Arbitrary [customerIds] for Parameter of type [@net.jqwik.api.ForAll(value="customerIds", supplier=net.jqwik.api.ArbitrarySupplier$NONE.class) String]`

**Comment by jlink** [comment]
At first glance it looks like it should work. I’ll have a closer look at it tomorrow.

**Comment by jlink** [comment]
At second glance it works as designed :-)
Provider methods from domains are not being looked up by name but by type. That means that all you have to do is:

```java
@Property
fun fail(@ForAll s: String) {
        s shouldNotHaveLength 0
}
```

If you want, you can apply the domain to a single property:

```java
@Domain(MyDomain::class)
@Property
fun fail(@ForAll s: String) {
        s shouldNotHaveLength 0
}
```

**Comment by lmartelli** [comment]
Thanks for the qwik feedback.

However, the purpose of DomainContext being to group arbitrary providers, arbitrary configurators and reporting formats in order to share them, this design leads to a problematic limitation in my opinion. You may want to have different providers for the same type and differentiate using names, and this use case is really cumbersome with the current design. The domain context is only really useful if it has has all the features and the same behaviours as "inline" declarations.

**Comment by jlink** [comment]
Domains are not the best choice for re-using general-purpose arbitrary providers. 
You may want to look at [Arbitrary Suppliers](https://jqwik.net/docs/current/user-guide.html#arbitrary-suppliers) instead.
