### ISSUE TITLE
Providing both @BeforeProperty and @BeforeTry throws a NullPointerException

### ISSUE THREAD

**Issue by adam-waldenberg** [jlink/jqwik#409]
## Testing Problem

I was playing around with the lifecycle and forgot to add a method to my `@BeforeProperty` annotation, resulting in the following:

```java
	@BeforeProperty
	/* Woops, where did the method go? :P */

	@BeforeTry
	public void beforeTry() {
		...
	}
```

This currently throws a `NullPointerException` with each test method (one being a `@Property` and the other being an `@Example` in this case) failing spectacularly: 

![image](https://user-images.githubusercontent.com/1555683/201506383-6d5fe837-9c1a-43b6-ad0b-708af1491359.png)

I'm guessing the `@After*` equivalents probably have the same issue?

## Suggested Solution

While it's certainly logically possible someone would like to run a method under both stages of the lifecycle (property and try), it doesn't really make much sense and its likely a mistake - like in this case.  I think JQwik should catch this and spit out an error.

**Comment by jlink** [comment]
I'm surprised by the NPE, thanks for the catch, @adam-waldenberg!

I'm wondering though if throwing an error is the right thing to do. First, it would break orthogonality of two features (before property and before try annotations) and second, it would require to write code for this exact mis(?)-configuration. To be frank, there are so many potential combinations of features and annotations that don't make sense, that tackling a single one of them seems a bit futile to me.

My suggestion: 
- The combination of more than one lifecycle annotation should just work.
- Let's add a more general issue of detecting and warning about potential mis-use of features. 
  Maybe by enabling "plausability rules" which can be added / removed via SPI.

What do you think?

**Comment by adam-waldenberg** [comment]
Yeah there are a lot of them for sure... It might be a better solution.... I would say step one is to just get rid of the NPE and allow them to work together then.

As a complement or alternative to the plausability rules - another option for handling this could be to support something like `@SuppressWarnings({"jqwik.message.name",...})` and allow that to be added method-wide or class-wide to just suppress these warnings on demand.

**Comment by jlink** [comment]
I think`@SuppressWarnings` has a `Source`  retention policy. So it would require some kind of after compiliation step.
Other libs come with their own variants of `@SuppressWarnings` annotation, presumedly to mitigate this.

**Comment by adam-waldenberg** [comment]
Yeah. Some tools, like for example PMD use it though, but thats because in PMD's case it's a source level analyzer anyway. In this case a `@SuppressJqwikWarnings` would probably be needed to acheive the same thinng. Spotbugs for example has `@SuppressFBWarnings`.

**Comment by jlink** [comment]
I cannot reproduce the problem. The following code works on my machine:

```java
public class Experiments {
	@BeforeProperty
	@BeforeTry
	void beforeProperty() {
		System.out.println("before property and try");
	}

	@Property
	void test(@ForAll String aString) {
		System.out.println(aString);
	}
}
```

@adam-waldenberg Can you put up a reproducing example?

**Comment by adam-waldenberg** [comment]
I have hooks defined as well - so it might be those that are triggering it. Didn't really check that closely. If you are unable to track it down I can look at doing a pull request for the test suite once I have some time over.

**Comment by jlink** [comment]
I don’t need a PR, a failing test would suffice. Of course, what suits you best.

**Comment by jlink** [comment]
@adam-waldenberg Any updates here?

**Comment by adam-waldenberg** [comment]
@jlink Not yet. I will let you know what I find when I look into it

**Comment by adam-waldenberg** [comment]
So a status update on this one.... Did some playing around and am unable to reproduce this again.... I'm going to have to go back to the old code and see if I can make this happen again because it seems it's being triggered by more than just the above condition.

Closing this for now. If I can figure out the exact prerequisites to trigger the NPE I will reopen it.
