### ISSUE TITLE
Javadocs and source files are missing on Central

### ISSUE THREAD

**Issue by vlsi** [jlink/jqwik#452]
## Testing Problem

The files exist, however, they are empty.
See jqwik-1.7.2-javadoc.jar and jqwik-1.7.2-sources.jar https://repo1.maven.org/maven2/net/jqwik/jqwik/0.9.3/

It causes javadoc badge to show up as `0.9.3` being the latest (see https://github.com/jlink/jqwik/pull/451)

**Comment by jlink** [comment]
The reason is that the `jqwik` module is only an aggregate artefact without source code. What do you suggest to change?

**Comment by vlsi** [comment]
Fine then.
