### ISSUE TITLE
Add todo method to fail parts which need to be done

### ISSUE THREAD

**Issue by gtrefs** [jlink/jqwik#5]
## Testing Problem

The problem is actually not specific to the test engine itself. The idea is to have some utility to indicate that some part of the application still needs some work. For example:

```Java
public String readArbitraryStuffFromSomeStreamAndReturnItAsString(Stream wellBehavingStream){
  return todo();
}
```
In this way one is able to compile the code while still failing the parts which need refurbishment.  

## Suggested Solution
```Java
public static <E> E todo(){
   throw new UnsupportedOperationsExcpetion();
}
```

## Discussion

The advantages I have in mind are the following:
* Indicates what parts need to be done before comitting
If the local tests fail, this is a clear indicator that the part of the code is not ready to commit. This is better than having a  TODO comment which does not have an effect on the build.
* Code compiles and thus executes other tests
Depending on the used compiler, code will not be executed unless everything compiles. While this property might be used in TDD, it still has some burden. Especially in the case of example based testing, the happy path might be implemented but the corner cases are not yet tested. 

The disadvantages I can think of are:
* Mixin of test dependency into production code
In order to compile properly the `todo` method needs to be part of the production code. Actually, this should not be the case because production would have a hard dependency on test libraries.

**Comment by jlink** [comment]
What's the drawback of just throwing the exception?

**Comment by gtrefs** [comment]
`todo` has less code and a well defined semantics: An operation is unsupported because it still needs to be done.

**Comment by jlink** [comment]
The semantics could be tackled by an appropriate exception message.

So the questions to ponder are: 
- Is the saved code worth an additional dependency - and an additional artefact? 
- Does the todo-method fit the purpose of a test engine?

I'm currently leaning towards no for both but that's just my gut speaking. 

Von meinem iPad gesendet

**Comment by gtrefs** [comment]
You are right. It does not really fit the purpose of a test engine. I just found the idea quite appealing, because `vavr`, Scala and Kotlin have such a method. But of course, in the environment of a test engine this is unfitting.

**Comment by jlink** [comment]
Ok. Since we agree I close it.
