### ISSUE TITLE
Every X years in @YearRange

### ISSUE THREAD

**Issue by derTobsch** [jlink/jqwik#509]
## Testing Problem

I want to get every fifth year from 1945 until 1989 (`@YearRange(min = 1945, max = 1989)`). So the output should be 1945, 1950, 1955, 1960, ... until 1985.

Is there a way to achieve this?

**Comment by jlink** [comment]
Not with annotations but using something like:

```java
	@Provide
	Arbitrary<Year> everyFifthYear() {
		return Dates.years().between(1945, 1989)
				   .filter( year ->  year.getValue() % 5 == 0);
	}
```

should do it.
