### ISSUE TITLE
Support for ad hoc usage

### ISSUE THREAD

**Issue by thyming** [jlink/jqwik#51]
## Testing Problem
Hi, I'm wondering if there's a straightforward way to use jqwik in an ad-hoc manner. By this I mean being able to use its random data generation utilities without having to use the jqwik junit engine to run tests. The specific use case I have is running integration tests in Spring while wanting to reuse the domain-specific arbitrary providers I've written.

## Suggested Solution

An API for creating a single sample of a given `Arbitrary<T>`, or an `@ArgumentsSource` for injecting values via `@ParametrizedTest`.

Thanks for this library, it's great!

**Comment by thyming** [comment]
Sorry, this is probably a duplicate of #41, feel free to close if you think so.

**Comment by jlink** [comment]
I think what you want can be done using arbitrary.generator(1000).stream(new Random()) 

Would that work for your purpose()?

**Comment by thyming** [comment]
oh yeah, that'll do it i think, thank you!

**Comment by luvarqpp** [comment]
Note, `Arbitrary<T>` type now have experimental methods [`Arbitrary<T>.sample()`](https://jqwik.net/docs/1.2.2/javadoc/net/jqwik/api/Arbitrary.html#sample--) and [`Arbitrary<T>.samplesStream()`](https://jqwik.net/docs/1.2.2/javadoc/net/jqwik/api/Arbitrary.html#samplesStream--) for convenient use. See https://github.com/jlink/jqwik/issues/76#issuecomment-566958263 for some discussion and its introduction.

PS: Do not be mistaken by `Arbitraries.samples(...)` method, which is similar by syntax, but does have way different purpose (it creates Arbitrary instance with passed possible values). Example usage in "oneliner": `Arbitraries.samples("asdf", "qwertz", "qwerty").sampleStream().limit(42).forEach(x -> System.out.println(x));`
