### ISSUE TITLE
JRE dependent "whitespace" generation

### ISSUE THREAD

**Issue by tmohme** [jlink/jqwik#55]
## Testing Problem

Unfortunately what is considered as whitespace character (`Character.isWhitespace(...)`) has changed between Java 8 (OpenJDK) and Java 11 (OpenJDK):  
In particular the U+180E ([Mongolian Vovel Separator](https://unicode.org/cldr/utility/character.jsp?a=180e&B1=Show)) counts in Java 8 as whitespace, while it does not in Java 11.  

This causes problems because when generating whitespace chars with jqwik (which contains hard-coded lists of whitespace chars based on Java 8) and actually running the functionality on Java 11.

## Suggested Solution

Instead of using a prepared, hard-coded list of whitespace chars, the chars considered as whitespace by the actual runtime should be used.  
Please have a look at my corresponding pull request.

## Discussion

To minimize the runtime overhead, the determination of the whitespace chars could (should) be done at class-level instead of instance-level.

**Comment by jlink** [comment]
Implemented with https://github.com/jlink/jqwik/commit/64cfac057e0df2cd6be82c65878825a71c4c5c30

**Comment by jlink** [comment]
Available in 1.1.3-SNAPSHOT

**Comment by jlink** [comment]
Released in 1.1.3
