### ISSUE TITLE
Enhance documentation and accessibility with code examples explaining the rationale

### ISSUE THREAD

**Issue by gtrefs** [jlink/jqwik#6]
## Testing Problem

Currently a lot of code is written with a specific mindset about testing. For example, there are specifications, examples and property based tests. It would be nice to have some code examples which explain the rationale. 

## Suggested Solution

Create an own source set or project which contains examples showcasing each feature.
For example, in case of property based tests, the FizzBuzz example could be copied into this source set. Futher, some additional links to property based tests could be provided.

## Discussion

I think in this way it would be easier to access jqwik. Currently, there are some ideas in this engine I am unfimiliar with. It would help me a lot to see the features in action and to derive own solutions from it.

**Comment by gtrefs** [comment]
Nevermind, just found the examples in test. It was confused that there is an `example` source set and an `examples` package in test.

**Comment by jlink** [comment]
You're right that documentation needs a lot of improvement. The examples package is a beginning at best. My plan is to invest into documentation over summer. You're welcome to help of course :)

Von meinem iPad gesendet

**Comment by jlink** [comment]
Add a few pages to document the common features. Maybe the classes in examples package should be extracted into source set of its own.

**Comment by gtrefs** [comment]
Maybe it would also make sense to open a gitter channel? Would be nice to have discussion ground beneath the github issue tracker.

**Comment by jlink** [comment]
Can you have a look at the current documentation and tell me if it covers your needs?

http://jqwik.net/user-guide.html

**Comment by DennisRippinger** [comment]
I have problems comprehending the section about [combining arbitraries](http://jqwik.net/user-guide.html#combining-arbitraries), the example is not using a combiner at all.

**Comment by jlink** [comment]
Thanks for the catch. Looks like I messed up the documentation examples.
Will fix it.

2017-11-12 22:12 GMT+01:00 Dennis Rippinger <notifications@github.com>:

**Comment by jlink** [comment]
@DennisRippinger I fixed it. Have a look!

**Comment by DennisRippinger** [comment]
Much better, thanks

**Comment by gtrefs** [comment]
Looks pretty solid to me. However, in [`How to use`](http://jqwik.net/user-guide.html#how-to-use) you say that the engine can be used with other engines. Can you provide an example for this? A quick glance into the JUnit 5 docs did not reveal to me how I can run two engines on the same codebase.

Maybe a little [migration guide](http://junit.org/junit5/docs/current/user-guide/#migrating-from-junit4-running) would be helpful?

**Comment by jlink** [comment]
@gtrefs Added a little bit in user guide about combining with other engines.
Migration guide would be an involved endeavour and thus require a new issue...

Closing this issue. Please create a new one for specific ideas about documentation.
