### ISSUE TITLE
Tutorial on programming your own generators

### ISSUE THREAD

**Issue by 3nigm4** [jlink/jqwik#7]
## Program your own Generators and Arbitraries

Hello Johannes Link, I find myself checking the site everyday to see whether there is already a tutorial on how to program your own generators. I also wonder whether there could be synergy with a project like https://github.com/benas/random-beans ? Thanks for this exciting project!

**Comment by jlink** [comment]
Does http://jqwik.net/user-guide.html#combining-arbitraries suit your needs? It's not really a tutorial but gives an example for a domain-specific arbitrary.

What type of generators are you thinking of?

As for the synergy with random-beans: For generators to fit into jqwik they must provide the appropriate shrinking behaviour which an 3rd party could only do if it is build on top of jqwik.
Which aspects of random-beans are most valuable to you?

**Comment by 3nigm4** [comment]
Hello thanks for your quick reply! [quick confession: junior java dev and also never really used tdd/pbt, but eager to learn]
## Thinking of:
I just want to be able to generate RandomObjects for testing purposes (they are a little bit more involved like a "Person" class with e.g.  "List<Contacts>" ... ).
## Goal:
My idea was to have a tdd workflow where I always implement jqwik generator for classes i make in order to quickly go "makeRandomConsistentInstance()"
I also want to learn all the capabilities of jqwik really well!
