### ISSUE TITLE
Initialization takes long time

### ISSUE THREAD

**Issue by owickstrom** [jlink/jqwik#70]
## Testing Problem

The initialization of the following property takes a long time (15-20 seconds on my laptop). Reducing the number of generators passed to `oneOf` inside `anyDateAndBirthDate` reduces the time it takes.

```java
package repro;

import net.jqwik.api.*;

import java.time.LocalDate;
import java.time.Month;
import java.time.YearMonth;

public class ReproductionTest {

  @Property
  void slow(
    @ForAll("anyDateAndBirthDate") Dates dates
  ) {
  }

  @Provide
  Arbitrary<Dates> () {
    return anyDates().flatMap(today ->
      Arbitraries.oneOf(
        datesBetween(today.minusYears(150), today.minusYears(1)),
        datesBetween(today.minusYears(200), today.minusYears(151)),
        datesBetween(today.plusYears(1), today.plusYears(5)),
        datesBetween(
          today.minusYears(18).minusDays(2),
          today.minusYears(18).plusDays(2)
        )
      ).map(birthDate -> new Dates(today, birthDate))
    );
  }

  Arbitrary<LocalDate> datesBetween(LocalDate low, LocalDate high) {
    return Arbitraries.integers()
      .between(low.getYear(), high.getYear())
      .flatMap(year ->
        Arbitraries.integers().between(
          year.equals(low.getYear()) ? low.getMonthValue() : 1,
          year.equals(high.getYear()) ? high.getMonthValue() : 12
        ).map(Month::of).flatMap(month -> {
          var yearMonth = YearMonth.of(year, month);
          return Arbitraries.integers().between(
            year.equals(low.getYear()) && month.equals(low.getMonth())
              ? low.getDayOfMonth()
              : 1,
            year.equals(high.getYear()) && month.equals(high.getMonth())
              ? high.getDayOfMonth()
              : yearMonth.lengthOfMonth()
          ).map(day -> LocalDate.of(year, month, day));
        })
      );
  }

  @Provide
  Arbitrary<LocalDate> anyDates() {
    return datesBetween(
      LocalDate.of(1900, 1, 1),
      LocalDate.of(2020, 12, 31)
    );
  }

  public class Dates {
    public final LocalDate today;
    public final LocalDate birthDate;

    public Dates(LocalDate today, LocalDate birthDate) {
      this.today = today;
      this.birthDate = birthDate;
    }

    @Override
    public String toString() {
      return "Dates{" +
        "today=" + today +
        ", birthDate=" + birthDate +
        '}';
    }
  }
}
```

## Suggested Solution

Don't have one. :)

**Comment by jlink** [comment]
@owickstrom Thanks for the issue. 

One little piece of progress in current snapshot 1.2.0-SNAPSHOT already: If you annotate the property like that:

	@Property(generation = GenerationMode.RANDOMIZED)

generation will start immediately since the delay creating initialization can be skipped.
Will keep you posted.

**Comment by owickstrom** [comment]
Nice! Can I also put that as default in the jqwik.properties and have the same behavior for all my properties?

**Comment by jlink** [comment]
Bad news and good news.

### Bad news #1 
GenerationMode default cannot be controlled in jqwik.properties. I agree that it should though.

### Good news

It's no longer necessary in your case to make the generation mode explicit since exhaustive generation detection will be shortcut much earlier and without noticable delay.

### Bad news #2

1.2.1 will not be released for some time (probably till September) so you'll have to use the snapshot version available on https://oss.sonatype.org/content/repositories/snapshots.
I only publish stable snapshots so that's usually not a problem in terms of stability.

**Comment by jlink** [comment]
Configuration of generation mode is now also possible: https://jqwik.net/docs/snapshot/user-guide.html#jqwik-configuration

**Comment by owickstrom** [comment]
Very cool, I'll try the snapshot when I get the time. Thanks!

**Comment by owickstrom** [comment]
Confirmed now that it works with the snapshot version. From 17s down to 500ms. Thanks again! :+1:

**Comment by jlink** [comment]
@owickstrom jqwik 1.2.1 has been released with this fix
