### ISSUE TITLE
Rework jqwik.net Homepage

### ISSUE THREAD

**Issue by jlink** [jlink/jqwik#82]
Following the discussion with @luvarqpp in https://github.com/jlink/jqwik/issues/81#issuecomment-567834207 a rework of jqwik.net seems necessary.

**Comment by luvarqpp** [comment]
I have this in my low priority TODO list and I hope that 3.2.2020 I will make some draft pull request for main page of jqwik.

**Comment by jlink** [comment]
Closing for now. Feel free to reopen if you get to it.
