### ISSUE TITLE
Typo in doc @AfterContainer

### ISSUE THREAD

**Issue by EdoardoVignati** [jlink/jqwik#96]
Hi. I would to point out the following chapter:
[https://jqwik.net/docs/current/user-guide.html#annotated-lifecycle-methods](https://jqwik.net/docs/current/user-guide.html#annotated-lifecycle-methods)

I think there is a typo in AfterContainer:
**@BeforeContainer**: Static methods with this annotation will run exactly once **before** any property will be executed, even before the first instance of this class will be created.
**@AfterContainer**: Static methods with this annotation will run exactly once **before**  any property will be executed, even before the first instance of this class will be created.

**Comment by jlink** [comment]
Damn CaP. Thanks for the catch. Will be fixed in 1.2.7.

**Comment by jlink** [comment]
Fixed in current user-guide and template for future versions: https://jqwik.net/docs/current/user-guide.html#annotated-lifecycle-methods
